"""Shared palette and SVG helpers for the Akira / 80s-anime art direction.

Every sample in this folder is generated by build.py from these helpers so the
palette and the layer structure (glow-back, base, shadow, highlight, ink, glow)
stay identical across assets. See docs/art-style.md for the rules.
"""
import math

# ---------------------------------------------------------------- palette ---
# Night / sky
NIGHT_0 = "#070A16"   # blue-black, deepest sky
NIGHT_1 = "#0E1424"   # blue-black, default backdrop
INDIGO_0 = "#1A1F45"  # indigo
INDIGO_1 = "#2A2E6B"  # lit indigo (planets, far structures)
DUSK = "#3A2A5C"      # dusk violet (horizon band)

# Hero (player): Kaneda red
RED = "#D8232C"
RED_SH = "#86121F"
RED_HI = "#FF5B45"    # warm kick on red only (rarely needed; prefer BONE)

# City glow: sodium
SODIUM = "#F2862B"
AMBER = "#FFB43C"
SODIUM_SH = "#A9481A"

# Neon
TEAL = "#1FB5B9"
CYAN = "#6EF2EE"
TEAL_SH = "#0F5E6A"

# Accent (sparingly)
MAGENTA = "#FF2E88"
MAGENTA_SH = "#8E1450"

# Ink + highlight
INK = "#140C14"       # warm near-black outline, never pure #000
BONE = "#F4EAD4"      # off-white highlight / kicks / type

# Neutral metal for the player's secondary parts
GUN = "#2C2D40"
GUN_SH = "#1A1A28"
GUN_HI = "#5A5C78"

# Enemy family (cold / sickly / hostile)
STEEL = "#5A6A88"
STEEL_SH = "#262D44"
STEEL_HI = "#A3B4CC"
BRUISE = "#74409A"
BRUISE_SH = "#3A1E52"
BRUISE_HI = "#A86CD0"
BILE = "#8FA84E"
BILE_SH = "#3E5229"
BILE_HI = "#D4E68E"
BILE_LIGHT = "#C8FF3A"

# Hazard rock
ROCK = "#605878"
ROCK_SH = "#2C2638"
ROCK_HI = "#958AA4"

# Pickups
HEAL = "#2EE6A6"
HEAL_SH = "#0E5A50"
HEAL_DEEP = "#0A3238"


# ---------------------------------------------------------------- helpers ---
def f(v):
    return f"{v:.1f}".rstrip("0").rstrip(".")


def pts(points):
    return " ".join(f"{f(x)},{f(y)}" for x, y in points)


def poly(points, fill, extra=""):
    return f'<polygon points="{pts(points)}" fill="{fill}" {extra}/>'


def inkpoly(points, w, color=INK, extra=""):
    return (f'<polygon points="{pts(points)}" fill="none" stroke="{color}" '
            f'stroke-width="{f(w)}" stroke-linejoin="round" {extra}/>')


def line(points, w, color=INK, extra=""):
    return (f'<polyline points="{pts(points)}" fill="none" stroke="{color}" '
            f'stroke-width="{f(w)}" stroke-linejoin="round" stroke-linecap="round" {extra}/>')


def mirror(half, cx):
    """half: outline from the top centre down one side. Returns closed outline."""
    return half + [(2 * cx - x, y) for x, y in reversed(half)]


def mx(points, cx):
    return [(2 * cx - x, y) for x, y in points]


def xf(points, cx=0, cy=0, sx=1, sy=1, dx=0, dy=0, rot=0):
    """Scale about (cx, cy), rotate (deg), then translate."""
    c, s = math.cos(math.radians(rot)), math.sin(math.radians(rot))
    out = []
    for x, y in points:
        x0, y0 = (x - cx) * sx, (y - cy) * sy
        out.append((cx + x0 * c - y0 * s + dx, cy + x0 * s + y0 * c + dy))
    return out


def star(cx, cy, r_out, r_in, n, rot=0, jitter=None):
    out = []
    for i in range(n * 2):
        r = r_out if i % 2 == 0 else r_in
        if jitter:
            r *= jitter[i % len(jitter)]
        a = math.radians(rot + i * 180 / n - 90)
        out.append((cx + r * math.cos(a), cy + r * math.sin(a)))
    return out


def ngon(cx, cy, r, n, rot=0, sx=1, sy=1):
    return [(cx + r * sx * math.cos(math.radians(rot + i * 360 / n - 90)),
             cy + r * sy * math.sin(math.radians(rot + i * 360 / n - 90))) for i in range(n)]


def layers(base="", shadow="", highlight="", ink="", glow="", glow_back=""):
    """The fixed layer stack every sprite uses (see art-style.md, SVG authoring)."""
    out = []
    if glow_back:
        out.append(f'<g id="glow-back">{glow_back}</g>')
    out.append(f'<g id="base">{base}</g>')
    out.append(f'<g id="shadow">{shadow}</g>')
    out.append(f'<g id="highlight">{highlight}</g>')
    out.append(f'<g id="ink">{ink}</g>')
    if glow:
        out.append(f'<g id="glow">{glow}</g>')
    return "\n".join(out)


GLOW_DEFS = """
<filter id="glowS" x="-100%" y="-100%" width="300%" height="300%"><feGaussianBlur stdDeviation="2"/></filter>
<filter id="glowM" x="-100%" y="-100%" width="300%" height="300%"><feGaussianBlur stdDeviation="5"/></filter>
<filter id="glowL" x="-100%" y="-100%" width="300%" height="300%"><feGaussianBlur stdDeviation="12"/></filter>
"""


def svg(w, h, body, comment="", defs=""):
    c = f"<!-- {comment} -->\n" if comment else ""
    return (f'<?xml version="1.0" encoding="UTF-8"?>\n{c}'
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}">\n'
            f'<defs>{GLOW_DEFS}{defs}</defs>\n{body}\n</svg>\n')


def embed(body, vb_w, vb_h, x, y, w, h, extra=""):
    """Place another sprite's body inside a composition (nested viewport)."""
    return (f'<svg x="{f(x)}" y="{f(y)}" width="{f(w)}" height="{f(h)}" '
            f'viewBox="0 0 {vb_w} {vb_h}" overflow="visible" {extra}>{body}</svg>')


def glow_dot(cx, cy, r, color, filt="glowS", core=BONE, op=0.9):
    return (f'<circle cx="{f(cx)}" cy="{f(cy)}" r="{f(r * 2.2)}" fill="{color}" opacity="{op}" filter="url(#{filt})"/>'
            f'<circle cx="{f(cx)}" cy="{f(cy)}" r="{f(r)}" fill="{color}"/>'
            f'<circle cx="{f(cx)}" cy="{f(cy)}" r="{f(r * 0.45)}" fill="{core}"/>')
