using System;
using System.IO;
using UnityEditor;
using UnityEditor.Build;
using UnityEngine;

// Wires the app icon (the "Orbital Rail" set) into Player Settings: the default
// icon (standalone / fallback), Android adaptive (background + foreground
// layers), round and legacy icons, and every iOS icon slot (incl. the 1024 App
// Store icon). The art is built by Art/AppIcon/src~/new_icon/build_icon.py and
// lives in one folder:
//
//   Art/AppIcon/OrbitalRail/OrbitalRail_1024.png             master, opaque (default icon)
//   Art/AppIcon/OrbitalRail/OrbitalRail_ios_1024.png         iOS, no alpha
//   Art/AppIcon/OrbitalRail/OrbitalRail_adaptive_fg_432.png  Android adaptive foreground (wordmark + ship)
//   Art/AppIcon/OrbitalRail/OrbitalRail_adaptive_bg_432.png  Android adaptive background (nebula, rails, planet)
//   Art/AppIcon/OrbitalRail/OrbitalRail_legacy_192.png       Android legacy (full composite)
//   Art/AppIcon/OrbitalRail/OrbitalRail_round_192.png        Android round (full composite)
//
// Re-runnable: Pause > App Icon > Apply Orbital Rail, or in batch mode:
//
//   Unity -batchmode -quit -projectPath Pause -executeMethod AppIconSetter.ApplyRecommended
//
// Each slot gets the one big texture; Unity scales it down per slot.
public static class AppIconSetter
{
    public const string Root = "Assets/Art/AppIcon";
    public const string Recommended = "OrbitalRail";
    public static readonly string[] Candidates = { "OrbitalRail" };

    // file part -> pixel size
    public const string Master = "1024", Ios = "ios_1024", AdaptiveFg = "adaptive_fg_432",
        AdaptiveBg = "adaptive_bg_432", Legacy = "legacy_192", Round = "round_192";
    public static readonly (string part, int size)[] Parts =
    {
        (Master, 1024), (Ios, 1024), (AdaptiveFg, 432), (AdaptiveBg, 432), (Legacy, 192), (Round, 192),
    };

    public static string PathOf(string ship, string part) { return Root + "/" + ship + "/" + ship + "_" + part + ".png"; }

    [MenuItem("Pause/App Icon/Apply Orbital Rail")] static void MenuOrbitalRail() { Apply("OrbitalRail"); }

    public static void ApplyRecommended() { Apply(Recommended); }

    // -executeMethod AppIconSetter.ApplyFromCommandLine [-appIcon <Ship>]
    public static void ApplyFromCommandLine()
    {
        string ship = Recommended;
        var args = Environment.GetCommandLineArgs();
        for (int i = 0; i < args.Length - 1; i++)
            if (args[i] == "-appIcon") ship = args[i + 1];
        Apply(ship);
    }

    static Texture2D Load(string ship, string part)
    {
        string path = PathOf(ship, part);
        var tex = AssetDatabase.LoadAssetAtPath<Texture2D>(path);
        if (tex == null)
        {
            AssetDatabase.ImportAsset(path);   // just regenerated by build_icon.py
            tex = AssetDatabase.LoadAssetAtPath<Texture2D>(path);
        }
        if (tex == null) throw new FileNotFoundException("App icon texture missing (run build_icon.py)", path);
        return tex;
    }

    public static void Apply(string ship)
    {
        if (Array.IndexOf(Candidates, ship) < 0)
            throw new ArgumentException("Unknown app icon candidate '" + ship + "' (one of " + string.Join(", ", Candidates) + ")");

        var master = Load(ship, Master);
        var ios = Load(ship, Ios);
        var fg = Load(ship, AdaptiveFg);
        var bg = Load(ship, AdaptiveBg);
        var legacy = Load(ship, Legacy);
        var round = Load(ship, Round);

        PlayerSettings.SetIcons(NamedBuildTarget.Unknown, new[] { master }, IconKind.Any);

        foreach (var kind in PlayerSettings.GetSupportedIconKinds(NamedBuildTarget.Android))
        {
            var icons = PlayerSettings.GetPlatformIcons(NamedBuildTarget.Android, kind);
            string k = AndroidKind(kind);
            foreach (var icon in icons)
            {
                if (k == "Adaptive") icon.SetTextures(bg, fg);   // layer 0 background, 1 foreground
                else if (k == "Round") icon.SetTexture(round);
                else icon.SetTexture(legacy);
            }
            PlayerSettings.SetPlatformIcons(NamedBuildTarget.Android, kind, icons);
        }

        foreach (var kind in PlayerSettings.GetSupportedIconKinds(NamedBuildTarget.iOS))
        {
            var icons = PlayerSettings.GetPlatformIcons(NamedBuildTarget.iOS, kind);
            foreach (var icon in icons) icon.SetTexture(ios);
            PlayerSettings.SetPlatformIcons(NamedBuildTarget.iOS, kind, icons);
        }

        AssetDatabase.SaveAssets();
        Debug.Log("[APPICON] applied " + ship);
    }

    // "Adaptive", "Round" or "Legacy" (Unity names them "Adaptive (API 26)",
    // "Round (API 25)", "Legacy"; matching by name keeps this file free of
    // the Android module's types).
    public static string AndroidKind(PlatformIconKind kind)
    {
        string name = kind.ToString();
        if (name.StartsWith("Adaptive")) return "Adaptive";
        if (name.StartsWith("Round")) return "Round";
        return "Legacy";
    }

    // The candidate the default icon currently comes from, or null.
    public static string Current()
    {
        var icons = PlayerSettings.GetIcons(NamedBuildTarget.Unknown, IconKind.Any);
        if (icons == null || icons.Length == 0 || icons[0] == null) return null;
        string path = AssetDatabase.GetAssetPath(icons[0]);
        foreach (var ship in Candidates)
            if (path == PathOf(ship, Master)) return ship;
        return null;
    }
}

// Import settings for the app-icon textures: full size, uncompressed, no
// mipmaps, and no alpha channel on the opaque ones (the iOS icon must not
// carry one).
public class AppIconImporter : AssetPostprocessor
{
    void OnPreprocessTexture()
    {
        if (!assetPath.StartsWith(AppIconSetter.Root + "/")) return;
        var importer = (TextureImporter)assetImporter;
        bool opaque = assetPath.EndsWith("_" + AppIconSetter.Master + ".png")
                      || assetPath.EndsWith("_" + AppIconSetter.Ios + ".png")
                      || assetPath.EndsWith("_" + AppIconSetter.AdaptiveBg + ".png");
        importer.textureType = TextureImporterType.Default;
        importer.mipmapEnabled = false;
        importer.npotScale = TextureImporterNPOTScale.None;
        importer.maxTextureSize = 1024;
        importer.textureCompression = TextureImporterCompression.Uncompressed;
        importer.filterMode = FilterMode.Bilinear;
        importer.wrapMode = TextureWrapMode.Clamp;
        importer.alphaSource = opaque ? TextureImporterAlphaSource.None : TextureImporterAlphaSource.FromInput;
        importer.alphaIsTransparency = !opaque;
        importer.isReadable = false;
    }
}
