#!/usr/bin/env python3
"""Codex UI art: parametric SVG sources + rasterized sprites + the C# palette.

Follows docs/art-style.md (80s anime, Akira 1988 palette, flat cartoon cels):
  * flat colour shapes, at most base + ONE hard shadow + ONE highlight kick
  * thick warm-black INK contour on every solid (4-5 u for UI plates),
    miter joins on UI, chamfers and wedges -- no rounded rects, pills, gloss,
    bevels or gradients
  * layer stack per sprite: base, shadow, highlight, ink (no glows on UI)
  * TEAL accents, Kaneda RED for highlights/selection, SODIUM/AMBER warm
    accents, MAGENTA at most once per screen (only the Pilot's Log art)

PALETTE below uses the style guide's names and hex values
(docs/art-samples/src/akira.py) and is the single source for the codex.
Running this script (or ./render.sh)
  1. writes every SVG next to it (this "~" folder is ignored by Unity),
  2. rasterizes them with resvg into Art/Resources/Codex (2x, sprite ppu 200,
     so one SVG unit == one UI canvas unit; entry art at 4x, ppu 400), and
  3. regenerates Scripts/Codex/CodexPalette.cs from the same values.

Requires resvg (brew install resvg).
"""
import math
import os
import shutil
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "../../../Resources/Codex"))
CS = os.path.normpath(os.path.join(HERE, "../../../../Scripts/Codex/CodexPalette.cs"))

# --------------------------------------------------------------------------
# Palette: style-guide name -> (C# name, hex, alpha)
# --------------------------------------------------------------------------
PALETTE = {
    "INK":       ("Ink", "#140C14", 1.0),         # every outline; locked blackout silhouettes
    "NIGHT_0":   ("Night0", "#070A16", 1.0),      # deepest
    "NIGHT_1":   ("Night1", "#0E1424", 1.0),      # UI panel fill
    "INDIGO_0":  ("Indigo0", "#1A1F45", 1.0),     # cards / idle tabs (the one shadow tone)
    "INDIGO_1":  ("Indigo1", "#2A2E6B", 1.0),     # locked edges
    "RED":       ("Red", "#D8232C", 1.0),         # Kaneda red: selection, highlights
    "RED_SH":    ("RedShadow", "#86121F", 1.0),
    "SODIUM":    ("Sodium", "#F2862B", 1.0),      # title, counters
    "AMBER":     ("Amber", "#FFB43C", 1.0),
    "SODIUM_SH": ("SodiumShadow", "#A9481A", 1.0),
    "TEAL":      ("Teal", "#1FB5B9", 1.0),        # primary UI accent
    "CYAN":      ("Cyan", "#6EF2EE", 1.0),
    "TEAL_SH":   ("TealShadow", "#0F5E6A", 1.0),
    "MAGENTA":   ("Magenta", "#FF2E88", 1.0),     # one accent per screen at most
    "BONE":      ("Bone", "#F4EAD4", 1.0),        # type, kicks (never #FFF)
    "STEEL_HI":  ("SteelHi", "#A3B4CC", 1.0),     # secondary / muted type
    "SCRIM":     ("Scrim", "#070A16", 0.88),      # full-screen dim behind the panel
}

def c(name):
    return PALETTE[name][1]

UI_INK = 5.0      # outer contour for UI plates (guide: 4 to 5 u)
PANEL_LINE = 2.0  # interior panel lines

# --------------------------------------------------------------------------
# Geometry + layered SVG
# --------------------------------------------------------------------------

def chamfer_pts(x, y, w, h, cuts):
    """Rect with straight corner cuts (tl, tr, br, bl)."""
    tl, tr, br, bl = cuts
    return [(x + tl, y), (x + w - tr, y), (x + w, y + tr), (x + w, y + h - br),
            (x + w - br, y + h), (x + bl, y + h), (x, y + h - bl), (x, y + tl)]

def pts(p):
    return " ".join("%.2f,%.2f" % q for q in p)

def inset(cuts, d):
    k = d * 0.4142   # keeps a 45-degree chamfer parallel when inset by d
    return tuple(max(0.0, cut - k) for cut in cuts)

class Sprite:
    """Collects shapes into the guide's layer stack."""
    def __init__(self, w, h):
        self.w, self.h = w, h
        self.layers = {"base": [], "shadow": [], "highlight": [], "ink": []}

    def poly(self, layer, p, fill="none", stroke=None, width=0, join="miter"):
        s = '<polygon points="%s" fill="%s"' % (pts(p), fill)
        if stroke:
            s += ' stroke="%s" stroke-width="%.2f" stroke-linejoin="%s"' % (stroke, width, join)
        self.layers[layer].append(s + "/>")

    def raw(self, layer, s):
        self.layers[layer].append(s)

    def svg(self, note):
        body = "\n".join('  <g id="%s">%s</g>' % (k, "".join(v)) for k, v in self.layers.items() if v)
        return ('<?xml version="1.0" encoding="UTF-8"?>\n<!-- %s\n     Generated by make_art.py from the '
                'docs/art-style.md palette - edit the script, not this file. -->\n'
                '<svg xmlns="http://www.w3.org/2000/svg" width="%g" height="%g" viewBox="0 0 %g %g">\n%s\n</svg>\n'
                % (note, self.w, self.h, self.w, self.h, body))

def plate(sp, cuts, base, ink=UI_INK, shadow=None, kick=True):
    """A flat UI plate: base fill, a hard shadow strip along the lower-right
    edges (light from the upper left), a BONE kick on the top-left edge, and
    the INK contour."""
    w, h = sp.w, sp.h
    i = ink / 2.0
    outline = chamfer_pts(i, i, w - ink, h - ink, inset(cuts, i))
    sp.poly("base", outline, fill=base)
    if shadow:
        t = 5.0
        sp.poly("shadow", [(w - ink, cuts[1] + ink), (w - ink, h - cuts[2] - ink), (w - cuts[2] - ink, h - ink),
                           (cuts[3] + ink, h - ink), (cuts[3] + ink + t, h - ink - t),
                           (w - cuts[2] - ink - t * .6, h - ink - t), (w - ink - t, h - cuts[2] - ink - t * .6),
                           (w - ink - t, cuts[1] + ink + t)], fill=shadow)
    if kick:
        k = 3.0
        x0 = ink + cuts[0] * .55 + 4
        sp.poly("highlight", [(x0, ink + 1), (x0 + 22, ink + 1), (x0 + 19, ink + 1 + k), (x0 - 3, ink + 1 + k)], fill=c("BONE"))
    sp.poly("ink", outline, stroke=c("INK"), width=ink)
    return outline

def rule(sp, cuts, ink=UI_INK, gap=4.0, width=3.0, colour="#ffffff"):
    """Inner accent rule (white template, tinted at runtime)."""
    d = ink + gap + width / 2.0
    sp.poly("highlight", chamfer_pts(d, d, sp.w - 2 * d, sp.h - 2 * d, inset(cuts, d)), stroke=colour, width=width)

# --------------------------------------------------------------------------
# Sprites: name -> (svg, zoom, 9-slice border in canvas units)
# --------------------------------------------------------------------------
SPRITES = {}

def add(name, sp, note, border=0, zoom=2):
    SPRITES[name] = (sp.svg(note), zoom, border)

# Panel frame: night plate, teal inner rule, a red tab notch top-left and an
# amber tick bottom-right (both inside the 9-slice corners).
P = 160
sp = Sprite(P, P)
CUTS = (34, 10, 34, 10)
plate(sp, CUTS, c("NIGHT_1"), shadow=c("INDIGO_0"), kick=False)
rule(sp, CUTS, gap=7, colour=c("TEAL"))
sp.poly("highlight", [(40, 0), (64, 0), (58, 9), (46, 9)], fill=c("RED"), stroke=c("INK"), width=2.5)
sp.poly("highlight", [(P - 60, P - 15), (P - 38, P - 15), (P - 41, P - 10), (P - 63, P - 10)], fill=c("AMBER"))
add("cx_panel", sp, "Codex panel frame - 9-slice, border 64u.", border=64)

# Card: one shadow tone body (INDIGO_0) with a cut top-right corner.
CARD = (0, 18, 0, 8)
sp = Sprite(96, 96)
plate(sp, CARD, c("INDIGO_0"), ink=4.5, shadow=c("NIGHT_1"))
add("cx_card", sp, "Codex card body - 9-slice, border 28u.", border=28)
sp = Sprite(96, 96)
rule(sp, CARD, ink=4.5)
add("cx_card_edge", sp, "Codex card inner rule - white, tinted per state - 9-slice, border 28u.", border=28)

# Button: angular slab; its edge layer adds a solid accent wedge on the left.
BTN = (18, 0, 18, 0)
sp = Sprite(96, 80)
plate(sp, BTN, c("INDIGO_0"), ink=5, shadow=c("NIGHT_1"))
add("cx_button", sp, "Codex button body - 9-slice, border 30u.", border=30)
sp = Sprite(96, 80)
rule(sp, BTN, ink=5)
sp.poly("highlight", [(12, 24), (20, 16), (20, 66), (12, 66)], fill="#ffffff")
add("cx_button_edge", sp, "Codex button inner rule + accent wedge - white, tinted - 9-slice, border 30u.", border=30)

# Tab / category tag: slanted cel, white base tinted at runtime (RED = selected).
sp = Sprite(56, 32)
o = chamfer_pts(2, 2, 52, 28, (10, 0, 10, 0))
sp.poly("base", o, fill="#ffffff")
sp.poly("ink", o, stroke=c("INK"), width=4)
add("cx_tab", sp, "Codex tab / tag - white base tinted at runtime, INK contour - 9-slice, border 14u.", border=14)

# Toast: small night plate with a sodium wedge on the left.
sp = Sprite(80, 48)
plate(sp, (12, 0, 12, 0), c("NIGHT_1"), ink=4.5, kick=False)
sp.poly("highlight", [(5, 17), (17, 5), (22, 5), (22, 43), (5, 43)], fill=c("SODIUM"))
sp.raw("ink", '<line x1="22" y1="5" x2="22" y2="43" stroke="%s" stroke-width="%g"/>' % (c("INK"), PANEL_LINE))
add("cx_toast", sp, "New-entry toast - 9-slice, border 24u.", border=24)

# Divider: hard teal rails with a red block in the middle.
sp = Sprite(440, 16)
for p in ([(0, 8), (12, 3), (208, 3), (208, 13), (12, 13)], [(440, 8), (428, 3), (232, 3), (232, 13), (428, 13)]):
    sp.poly("base", p, fill=c("TEAL"), stroke=c("INK"), width=PANEL_LINE)
sp.poly("highlight", [(212, 1), (228, 1), (228, 15), (212, 15)], fill=c("RED"), stroke=c("INK"), width=PANEL_LINE)
add("cx_divider", sp, "Header divider (not sliced).")

# Header marker: red chevron wedge.
sp = Sprite(32, 32)
m = [(4, 4), (18, 4), (28, 16), (18, 28), (4, 28), (14, 16)]
sp.poly("base", m, fill=c("RED"))
sp.poly("shadow", [(18, 28), (28, 16), (23, 16), (15, 25)], fill=c("RED_SH"))
sp.poly("ink", m, stroke=c("INK"), width=3)
add("cx_marker", sp, "Header marker chevron.")

# Glyphs.
sp = Sprite(32, 32)
sp.raw("ink", '<path d="M10 15 V9 H22 V15" fill="none" stroke="%s" stroke-width="7" stroke-linejoin="miter"/>' % c("INK"))
sp.raw("ink", '<path d="M10 15 V9 H22 V15" fill="none" stroke="#ffffff" stroke-width="3" stroke-linejoin="miter"/>')
sp.poly("ink", [(6, 14), (26, 14), (26, 28), (6, 28)], fill="#ffffff", stroke=c("INK"), width=3)
sp.raw("ink", '<rect x="14.5" y="18" width="3" height="6" fill="%s"/>' % c("INK"))
add("cx_lock", sp, "Locked glyph - white, tinted at runtime.")

sp = Sprite(64, 64)
chev = [(40, 10), (48, 18), (34, 32), (48, 46), (40, 54), (18, 32)]
sp.poly("base", chev, fill=c("BONE"))
sp.poly("shadow", [(34, 32), (48, 46), (40, 54), (37, 51), (43, 45)], fill=c("STEEL_HI"))
sp.poly("ink", chev, stroke=c("INK"), width=4)
add("cx_back", sp, "Back chevron.")

sp = Sprite(64, 64)
book = [(32, 18), (56, 12), (56, 50), (32, 56), (8, 50), (8, 12)]
sp.poly("base", book, fill=c("BONE"))
sp.poly("shadow", [(32, 18), (32, 56), (8, 50), (8, 12)], fill=c("STEEL_HI"))
sp.poly("ink", book, stroke=c("INK"), width=4)
sp.raw("ink", '<line x1="32" y1="18" x2="32" y2="56" stroke="%s" stroke-width="%g"/>' % (c("INK"), PANEL_LINE * 2))
sp.raw("ink", '<polygon points="42,8 50,6 50,26 46,22 42,27" fill="%s" stroke="%s" stroke-width="2.5" '
              'stroke-linejoin="miter"/>' % (c("RED"), c("INK")))
add("cx_book", sp, "Codex book glyph (BONE, one STEEL_HI shadow, red bookmark).")

sp = Sprite(64, 64)
sp.raw("base", '<circle cx="32" cy="32" r="31.5" fill="#ffffff"/>')
add("cx_circle", sp, "Round mask for world art (graphic hidden at runtime).")

# Entry art.
def blackhole():
    sp = Sprite(128, 128)
    ring = [(10, 70), (30, 56), (98, 50), (118, 58), (98, 72), (30, 78)]
    front = [(10, 70), (30, 78), (98, 72), (118, 58), (112, 66), (96, 80), (30, 86)]
    # The back half of the disc sits behind the horizon, so its contour is
    # drawn under the hole rather than in the top ink group.
    sp.poly("base", ring, fill=c("SODIUM"), stroke=c("INK"), width=4)
    sp.raw("base", '<circle cx="64" cy="62" r="26" fill="%s" stroke="%s" stroke-width="4"/>' % (c("NIGHT_0"), c("INK")))
    sp.poly("base", front, fill=c("SODIUM"))
    sp.poly("shadow", [(22, 78), (98, 72), (92, 79), (30, 84)], fill=c("SODIUM_SH"))
    sp.raw("highlight", '<path d="M46 60 A18 18 0 0 1 82 60" fill="none" stroke="%s" stroke-width="3"/>' % c("MAGENTA"))
    sp.poly("highlight", [(20, 69), (34, 62), (40, 62), (26, 69)], fill=c("AMBER"))
    ship = [(102, 16), (116, 30), (106, 30), (100, 38), (96, 26), (92, 22)]
    sp.poly("base", ship, fill=c("RED"))
    sp.poly("highlight", [(101, 21), (108, 27), (104, 28)], fill=c("BONE"))
    for p in (front, ship):
        sp.poly("ink", p, stroke=c("INK"), width=4)
    sp.raw("highlight", '<polyline points="84,40 94,32" stroke="%s" stroke-width="3"/>'
                        '<polyline points="88,46 98,38" stroke="%s" stroke-width="3"/>' % (c("CYAN"), c("CYAN")))
    sp.poly("highlight", [(20, 22), (23, 28), (20, 34), (17, 28)], fill=c("BONE"))
    sp.poly("highlight", [(108, 100), (111, 105), (108, 110), (105, 105)], fill=c("AMBER"))
    return sp
add("cx_blackhole", blackhole(), "Pilot's Log art: the black hole that swallowed the pilot.", zoom=4)

def octagon(r):
    return [(64 + r * math.cos(math.radians(22.5 + 45 * k)), 64 + r * math.sin(math.radians(22.5 + 45 * k)))
            for k in range(8)]

def wormhole():
    sp = Sprite(128, 128)
    for r, col, layer in ((54, c("NIGHT_1"), "base"), (42, c("TEAL"), "base"), (30, c("INDIGO_0"), "shadow"),
                          (18, c("TEAL_SH"), "shadow")):
        sp.poly(layer, octagon(r), fill=col)
    for r in (54, 42, 30, 18):
        sp.poly("ink", octagon(r), stroke=c("INK"), width=4)
    for x in (50, 68):
        sp.raw("ink", '<polygon points="%s" fill="%s" stroke="%s" stroke-width="4" stroke-linejoin="miter"/>'
               % (pts([(x, 44), (x + 10, 44), (x + 10, 84), (x, 84)]), c("BONE"), c("INK")))
    sp.raw("ink", '<polygon points="6,30 22,24 18,34" fill="%s" stroke="%s" stroke-width="2"/>' % (c("RED"), c("INK")))
    return sp
add("cx_wormhole", wormhole(), "Wormhole Gift art: the pause at the heart of the wormhole.", zoom=4)

# --------------------------------------------------------------------------
# Output
# --------------------------------------------------------------------------

def write_palette_cs():
    lines = [
        "using UnityEngine;",
        "",
        "// GENERATED by Art/UI/Codex/src~/make_art.py from its PALETTE table (the",
        "// docs/art-style.md names and hex values) -- edit the script and re-run it,",
        "// not this file. The codex sprites are rendered from the same values.",
        "public static class CodexPalette",
        "{",
    ]
    for guide, (name, hexv, a) in PALETTE.items():
        r, g, b = (int(hexv[i:i + 2], 16) / 255.0 for i in (1, 3, 5))
        lines.append("    public static readonly Color %s = new Color(%.3ff, %.3ff, %.3ff, %.2ff);   // %s %s"
                     % (name, r, g, b, a, guide, hexv))
    lines.append("}")
    open(CS, "w").write("\n".join(lines) + "\n")

def main():
    os.makedirs(OUT, exist_ok=True)
    for name, (text, zoom, border) in SPRITES.items():
        src = os.path.join(HERE, name + ".svg")
        open(src, "w").write(text)
        subprocess.check_call(["resvg", "--zoom", str(zoom), src, os.path.join(OUT, name + ".png")])
    # The two Pilot's Log illustrations are painted raster assets. Keep their
    # source PNGs beside this generator and install them after the UI vectors
    # are rendered so a routine Codex rebuild cannot restore the old glyph art.
    for name in ("cx_blackhole", "cx_wormhole"):
        raster = os.path.join(HERE, name + "_rugged.png")
        if os.path.isfile(raster):
            shutil.copyfile(raster, os.path.join(OUT, name + ".png"))
    write_palette_cs()
    with open(os.path.join(HERE, "borders.txt"), "w") as f:
        for name, (_, zoom, border) in SPRITES.items():
            f.write("%s %d %d\n" % (name, border * zoom, 100 * zoom))
    print("wrote %d sprites + CodexPalette.cs" % len(SPRITES))

if __name__ == "__main__":
    main()
