using UnityEngine;

// GENERATED by Art/UI/Codex/src~/make_art.py from its PALETTE table -- edit
// the script and re-run it, not this file. The codex art is rendered from
// the same values, so runtime tints and sprites always agree.
//
// 80s anime, Akira (1988) palette: deep indigo base, teal / sodium-orange
// accents, Kaneda red for highlights and selection, sparse magenta.
public static class CodexPalette
{
    public static readonly Color Ink = new Color(0.024f, 0.024f, 0.059f, 1.00f);
    public static readonly Color Night = new Color(0.043f, 0.047f, 0.149f, 1.00f);
    public static readonly Color Shadow = new Color(0.090f, 0.098f, 0.267f, 1.00f);
    public static readonly Color Slate = new Color(0.227f, 0.247f, 0.471f, 1.00f);
    public static readonly Color Teal = new Color(0.129f, 0.831f, 0.784f, 1.00f);
    public static readonly Color Sodium = new Color(1.000f, 0.549f, 0.102f, 1.00f);
    public static readonly Color SodiumShade = new Color(0.722f, 0.353f, 0.063f, 1.00f);
    public static readonly Color KanedaRed = new Color(0.890f, 0.125f, 0.173f, 1.00f);
    public static readonly Color Magenta = new Color(0.839f, 0.149f, 0.561f, 1.00f);
    public static readonly Color Paper = new Color(0.945f, 0.914f, 0.839f, 1.00f);
    public static readonly Color Muted = new Color(0.604f, 0.612f, 0.784f, 1.00f);
    public static readonly Color Scrim = new Color(0.020f, 0.020f, 0.059f, 0.86f);
}
