using UnityEngine;
using UnityEngine.UI;

// Shared look for the codex panel, its home-screen button and the in-run
// toast: flat 80s-anime cels in the Akira palette -- thick ink outlines,
// flat fills with at most one shadow tone, hard angular corners, no gloss.
// Sprites in Art/Resources/Codex and CodexPalette.cs are both generated by
// Art/UI/Codex/src~/make_art.py.
public static class CodexUi
{
    // Roles over CodexPalette (generated by make_art.py), so the code says what
    // a colour is for and the palette itself lives in one place.
    public static Color Accent { get { return CodexPalette.Teal; } }
    public static Color Title { get { return CodexPalette.Sodium; } }
    public static Color Select { get { return CodexPalette.Red; } }
    public static Color Ink { get { return CodexPalette.Ink; } }
    public static Color Muted { get { return CodexPalette.SteelHi; } }
    public static Color Body { get { return CodexPalette.Bone; } }
    public static Color Idle { get { return CodexPalette.Indigo0; } }
    public static Color Locked { get { return CodexPalette.Indigo1; } }
    // Undiscovered art: the sprite's own shape, blacked out in flat ink.
    public static Color Silhouette { get { return CodexPalette.Ink; } }

    // "Who's that Pokemon?": undiscovered art draws through this material,
    // which paints the Graphic's colour times the sprite's alpha and nothing
    // of the drawing itself (Shaders/Resources/CodexSilhouette). A plain colour
    // tint would multiply the art, letting its interior detail show through.
    public const string SilhouetteShaderPath = "CodexSilhouette/CodexSilhouette";
    static Material silhouetteMaterial;

    public static Material SilhouetteMaterial
    {
        get
        {
            if (silhouetteMaterial == null)
            {
                var shader = Resources.Load<Shader>(SilhouetteShaderPath);
                if (shader == null) return null;
                silhouetteMaterial = new Material(shader) { name = "CodexSilhouette", hideFlags = HideFlags.DontSave };
            }
            return silhouetteMaterial;
        }
    }

    // Shows `g` as a flat silhouette (locked) or in its own colours.
    public static void PaintArt(Graphic g, bool locked)
    {
        if (g == null) return;
        g.color = locked ? Silhouette : Color.white;
        var m = locked ? SilhouetteMaterial : null;
        // (Graphic.material reads back the default material when unset.)
        if (g.material != (m != null ? m : g.defaultMaterial)) g.material = m;
    }

    public static bool IsSilhouette(Graphic g)
    {
        return g != null && g.material != null && g.material == silhouetteMaterial && silhouetteMaterial != null;
    }

    public static Sprite CodexSprite(string name)
    {
        return Resources.Load<Sprite>("Codex/" + name);
    }

    // The game's UI font (Orbitron Bold) isn't under Resources; borrow it from
    // whatever Text the scene already has.
    public static Font FindFont()
    {
        foreach (var t in Object.FindObjectsByType<Text>(FindObjectsInactive.Include, FindObjectsSortMode.None))
            if (t.font != null && t.font.name.StartsWith("Orbitron")) return t.font;
        return Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
    }

    public static Image NewImage(string name, Transform parent, Sprite sprite, Color color, bool sliced = false)
    {
        var go = new GameObject(name, typeof(RectTransform), typeof(Image));
        go.transform.SetParent(parent, false);
        var img = go.GetComponent<Image>();
        img.sprite = sprite;
        img.color = color;
        img.raycastTarget = false;
        if (sliced) img.type = Image.Type.Sliced;
        return img;
    }

    // Gives an animated holder its own sub-canvas. A sprite swap dirties its
    // canvas and rebuilds that canvas's whole batch; on the panel's one big
    // canvas (dozens of outlined, best-fit texts and masks) a card swapping
    // frames nearly every frame made a long rebuild every frame -- the idle
    // loops hitched. In its own canvas only the art's few quads rebuild.
    // (No overrideSorting: it still draws in hierarchy order with its parent,
    // and the panel's RectMask2D / CanvasGroup alpha / scale still apply.)
    public static Canvas Isolate(GameObject go)
    {
        var c = go.GetComponent<Canvas>();
        if (c == null) c = go.AddComponent<Canvas>();
        return c;
    }

    public static Text NewText(string name, Transform parent, Font font, string content, int size, Color color,
                               TextAnchor align, bool wrap = false)
    {
        var go = new GameObject(name, typeof(RectTransform), typeof(Text));
        go.transform.SetParent(parent, false);
        var text = go.GetComponent<Text>();
        text.font = font;
        text.text = content;
        text.fontSize = size;
        text.fontStyle = FontStyle.Bold;
        text.color = color;
        text.alignment = align;
        text.horizontalOverflow = wrap ? HorizontalWrapMode.Wrap : HorizontalWrapMode.Overflow;
        text.verticalOverflow = VerticalWrapMode.Overflow;
        text.raycastTarget = false;
        return text;
    }

    public static RectTransform NewRect(string name, Transform parent)
    {
        var go = new GameObject(name, typeof(RectTransform));
        go.transform.SetParent(parent, false);
        return (RectTransform)go.transform;
    }

    public static void AddOutline(GameObject go, Color color, float distance)
    {
        var o = go.GetComponent<Outline>() ?? go.AddComponent<Outline>();
        o.effectColor = color;
        o.effectDistance = new Vector2(distance, -distance);
    }

    // Rect is in the parent's centre-origin space.
    public static void Place(RectTransform rt, Rect r)
    {
        rt.anchorMin = rt.anchorMax = rt.pivot = new Vector2(.5f, .5f);
        rt.anchoredPosition = r.center;
        rt.sizeDelta = r.size;
    }

    public static void Stretch(RectTransform rt)
    {
        rt.anchorMin = Vector2.zero; rt.anchorMax = Vector2.one;
        rt.offsetMin = rt.offsetMax = Vector2.zero;
    }

    public static Rect Centered(float x, float y, float w, float h)
    {
        return new Rect(x - w * .5f, y - h * .5f, w, h);
    }

    public static void SetAlpha(Graphic g, float a)
    {
        if (g == null) return;
        var c = g.color;
        if (Mathf.Approximately(c.a, a)) return;
        c.a = a;
        g.color = c;
    }

    public static float EaseOutCubic(float x) { x = Mathf.Clamp01(x); float i = 1f - x; return 1f - i * i * i; }

    public static float EaseOutBack(float x)
    {
        x = Mathf.Clamp01(x);
        const float c1 = 1.70158f, c3 = c1 + 1f;
        float m = x - 1f;
        return 1f + c3 * m * m * m + c1 * m * m;
    }

    // Overlay canvas whose units are at least 800x1280 on any screen that is
    // big enough in points / dp, so the codex keeps the same proportions as
    // the rest of the game's UI; on a small one (UiScale's floor: these
    // canvases lay out touch targets of >= TapUnits and type of >= TextUnits)
    // it has fewer units and everything built on it lays out from its size.
    public const float TapUnits = 96f, TextUnits = 15f;
    public static readonly Vector2 Reference = new Vector2(800f, 1280f);

    public static Canvas NewOverlayCanvas(string name, int sortingOrder, bool interactive)
    {
        return NewOverlayCanvas(name, sortingOrder, interactive, TapUnits, TextUnits);
    }

    // A canvas with no touch targets (a toast) states only its smallest type.
    public static Canvas NewOverlayCanvas(string name, int sortingOrder, bool interactive, float tapUnits, float textUnits)
    {
        var go = new GameObject(name, typeof(RectTransform), typeof(Canvas), typeof(CanvasScaler));
        var canvas = go.GetComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;
        canvas.sortingOrder = sortingOrder;
        var scaler = go.GetComponent<CanvasScaler>();
        scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
        scaler.screenMatchMode = CanvasScaler.ScreenMatchMode.Expand;
        UiScaleFloor.Configure(scaler, Reference, tapUnits, textUnits);
        if (interactive) go.AddComponent<GraphicRaycaster>();
        return canvas;
    }

    // The screen's safe area in the canvas's centre-origin units.
    public static Rect SafeAreaUnits(Canvas canvas)
    {
        var rect = ((RectTransform)canvas.transform).rect;
        float sf = Mathf.Max(canvas.scaleFactor, .0001f);
        Rect safe = ScreenInfo.SafeArea;
        return new Rect(safe.x / sf - rect.width * .5f, safe.y / sf - rect.height * .5f,
                        safe.width / sf, safe.height / sf);
    }
}
