using UnityEngine;

// GENERATED by Art/UI/Codex/src~/make_art.py from its PALETTE table (the
// docs/art-style.md names and hex values) -- edit the script and re-run it,
// not this file. The codex sprites are rendered from the same values.
public static class CodexPalette
{
    public static readonly Color Ink = new Color(0.078f, 0.047f, 0.078f, 1.00f);   // INK #140C14
    public static readonly Color Night0 = new Color(0.027f, 0.039f, 0.086f, 1.00f);   // NIGHT_0 #070A16
    public static readonly Color Night1 = new Color(0.055f, 0.078f, 0.141f, 1.00f);   // NIGHT_1 #0E1424
    public static readonly Color Indigo0 = new Color(0.102f, 0.122f, 0.271f, 1.00f);   // INDIGO_0 #1A1F45
    public static readonly Color Indigo1 = new Color(0.165f, 0.180f, 0.420f, 1.00f);   // INDIGO_1 #2A2E6B
    public static readonly Color Red = new Color(0.847f, 0.137f, 0.173f, 1.00f);   // RED #D8232C
    public static readonly Color RedShadow = new Color(0.525f, 0.071f, 0.122f, 1.00f);   // RED_SH #86121F
    public static readonly Color Sodium = new Color(0.949f, 0.525f, 0.169f, 1.00f);   // SODIUM #F2862B
    public static readonly Color Amber = new Color(1.000f, 0.706f, 0.235f, 1.00f);   // AMBER #FFB43C
    public static readonly Color SodiumShadow = new Color(0.663f, 0.282f, 0.102f, 1.00f);   // SODIUM_SH #A9481A
    public static readonly Color Teal = new Color(0.122f, 0.710f, 0.725f, 1.00f);   // TEAL #1FB5B9
    public static readonly Color Cyan = new Color(0.431f, 0.949f, 0.933f, 1.00f);   // CYAN #6EF2EE
    public static readonly Color TealShadow = new Color(0.059f, 0.369f, 0.416f, 1.00f);   // TEAL_SH #0F5E6A
    public static readonly Color Magenta = new Color(1.000f, 0.180f, 0.533f, 1.00f);   // MAGENTA #FF2E88
    public static readonly Color Bone = new Color(0.957f, 0.918f, 0.831f, 1.00f);   // BONE #F4EAD4
    public static readonly Color SteelHi = new Color(0.639f, 0.706f, 0.800f, 1.00f);   // STEEL_HI #A3B4CC
    public static readonly Color Scrim = new Color(0.027f, 0.039f, 0.086f, 0.88f);   // SCRIM #070A16
}
