#!/usr/bin/env python3
"""Writes icon_<name>.svg (the sources render.sh rasterises).

Akira / 80s-anime style (docs/art-style.md): a chamfered night plate with a
thick ink contour, one hard sheen facet and a red keyline; the glyph is flat
BONE with an INK outline and a hard RED cel drop shadow. No gradients, no
bloom. Every plate element sits on its own line marked class="plate" so
`render.sh --glyph` can strip it. The line `<!--SHINE-->` is where
`render.sh --shine` drops the idle shimmer band.
"""
import math
import os

NIGHT_1, INDIGO_0, INDIGO_1 = "#0E1424", "#1A1F45", "#2A2E6B"
RED, INK, BONE = "#D8232C", "#140C14", "#F4EAD4"


def f(v):
    return f"{v:.1f}".rstrip("0").rstrip(".")


def pts(p):
    return " ".join(f"{f(x)},{f(y)}" for x, y in p)


def chamfer(x, y, w, h, c):
    return [(x + c, y), (x + w - c, y), (x + w, y + c), (x + w, y + h - c),
            (x + w - c, y + h), (x + c, y + h), (x, y + h - c), (x, y + c)]


def plate():
    outer = chamfer(8, 8, 112, 112, 22)
    inner = chamfer(14, 14, 100, 100, 18)
    return [
        f'<polygon class="plate" points="{pts(outer)}" fill="{NIGHT_1}"/>',
        f'<polygon class="plate" points="{pts(inner)}" fill="{INDIGO_0}"/>',
        f'<polygon class="plate" points="14,32 32,14 58,14 14,58" fill="{INDIGO_1}"/>',
        "<!--SHINE-->",
        f'<polygon class="plate" points="{pts(inner)}" fill="none" stroke="{RED}" stroke-width="2" stroke-linejoin="miter" stroke-miterlimit="2.5"/>',
        f'<polygon class="plate" points="{pts(outer)}" fill="none" stroke="{INK}" stroke-width="5" stroke-linejoin="miter" stroke-miterlimit="2.5"/>',
    ]


def replay(dx, dy, col, w):
    cx, cy, r = 64 + dx, 66 + dy, 26
    angs = [-55 + k * 40 for k in range(8)]
    p = [(cx + r * math.cos(math.radians(a)), cy + r * math.sin(math.radians(a))) for a in angs]
    out = (f'<polyline points="{pts(p)}" fill="none" stroke="{col}" stroke-width="{w}" '
           f'stroke-linejoin="miter" stroke-linecap="butt"/>')
    a = math.radians(-55)
    ex, ey = p[0]
    tx, ty = math.sin(a), -math.cos(a)
    nx, ny = math.cos(a), math.sin(a)
    g = (w - 12) / 2
    hw, hl = 16 + g, 17 + g * 1.6
    head = [(ex + nx * hw, ey + ny * hw), (ex - nx * hw, ey - ny * hw), (ex + tx * hl, ey + ty * hl)]
    head = [(x - tx * g * 0.6, y - ty * g * 0.6) for x, y in head]
    out += f'<polygon points="{pts(head)}" fill="{col}" stroke="{col}" stroke-width="{f(max(0, w - 12) * 0.5)}" stroke-linejoin="miter" stroke-miterlimit="2.5"/>'
    return out


HOUSE = [(64, 28), (98, 58), (89, 58), (89, 96), (72, 96), (72, 76), (56, 76), (56, 96), (39, 96), (39, 58), (30, 58)]
PLAY = [(46, 32), (96, 64), (46, 96)]


def filled(shape):
    def draw(dx, dy, col, w):
        p = [(x + dx, y + dy) for x, y in shape]
        stroke = max(0, w - 12)
        return (f'<polygon points="{pts(p)}" fill="{col}" stroke="{col}" stroke-width="{f(stroke)}" '
                f'stroke-linejoin="miter" stroke-miterlimit="2.5"/>')
    return draw


def glyph(draw):
    # hard red cel offset, ink contour, flat BONE face
    return [draw(5, 5, RED, 22), draw(0, 0, INK, 22), draw(0, 0, BONE, 12)]


ICONS = {
    "replay": ("Replay (restart the run)", replay),
    "home": ("Home (leave to the main menu)", filled(HOUSE)),
    "play": ("Play (start a real run; the tutorial end card's PLAY). Only the glyph-only variant is rendered.", filled(PLAY)),
}


def write():
    here = os.path.dirname(os.path.abspath(__file__))
    for name, (what, draw) in ICONS.items():
        body = "\n  ".join(plate() + glyph(draw))
        svg = f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- Pause icon: {what}
     Akira / 80s-anime style (docs/art-style.md): chamfered NIGHT plate, INK
     contour, one INDIGO sheen facet, RED keyline; BONE glyph with an INK
     outline and a hard RED cel shadow. Generated by build_icons.py;
     rasterise with ./render.sh (also with the glyph and shine flags). -->
<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128">
  {body}
</svg>
'''
        with open(os.path.join(here, f"icon_{name}.svg"), "w") as fh:
            fh.write(svg)


if __name__ == "__main__":
    write()
