using System.IO;
using UnityEditor;
using UnityEditor.Build;
using UnityEngine;

// The app icon (Art/AppIcon, generated by src~/make_icon.py, wired by
// AppIconSetter):
//  - every candidate has all its files at the right pixel size, the opaque
//    ones (master, iOS, adaptive background) without an alpha channel;
//  - the adaptive foreground is transparent around the ship, and all of
//    it (hull, glow, exhaust) sits inside the 66 dp safe circle;
//  - Player Settings use the recommended candidate: default icon, Android
//    adaptive (background layer 0, foreground layer 1), round and legacy
//    icons, and every iOS slot with the alpha-free 1024;
//  - switching candidate is one call (applied and restored here).
public static class AppIconTest
{
    static int fails;
    static void Check(string what, bool ok)
    {
        Debug.Log((ok ? "[ICON] PASS  " : "[ICON] FAIL  ") + what);
        if (!ok) fails++;
    }

    public static void Run() { TestHarness.Exit(Execute()); }

    public static int Execute()
    {
        fails = 0;
        Check("the recommended icon is Gold Warden (Regent skin)", AppIconSetter.Recommended == "GoldWarden");
        foreach (var ship in AppIconSetter.Candidates) Files(ship);
        SafeZone(AppIconSetter.Recommended);
        PlayerSettingsUse(AppIconSetter.Recommended);

        string before = AppIconSetter.Current();
        try
        {
            AppIconSetter.Apply("Lightning");
            Check("switching: Apply(\"Lightning\") makes it current", AppIconSetter.Current() == "Lightning");
            PlayerSettingsUse("Lightning");
            AppIconSetter.Apply("NeonComet");
            Check("switching: Apply(\"NeonComet\") makes it current", AppIconSetter.Current() == "NeonComet");
            PlayerSettingsUse("NeonComet");
        }
        finally
        {
            AppIconSetter.Apply(before ?? AppIconSetter.Recommended);
        }
        Check("switching back restores " + AppIconSetter.Recommended, AppIconSetter.Current() == AppIconSetter.Recommended);
        return fails;
    }

    // PNG header: width, height, colour type (2 = RGB, 6 = RGBA).
    static bool Header(string path, out int w, out int h, out int colourType)
    {
        w = h = colourType = -1;
        if (!File.Exists(path)) return false;
        var b = new byte[26];
        using (var fs = File.OpenRead(path)) if (fs.Read(b, 0, 26) < 26) return false;
        if (b[1] != 'P' || b[2] != 'N' || b[3] != 'G') return false;
        w = (b[16] << 24) | (b[17] << 16) | (b[18] << 8) | b[19];
        h = (b[20] << 24) | (b[21] << 16) | (b[22] << 8) | b[23];
        colourType = b[25];
        return true;
    }

    static void Files(string ship)
    {
        foreach (var (part, size) in AppIconSetter.Parts)
        {
            string path = AppIconSetter.PathOf(ship, part);
            bool ok = Header(path, out int w, out int h, out int ct);
            Check(ship + " " + part + " exists", ok);
            if (!ok) continue;
            Check(ship + " " + part + " is " + size + "x" + size + " (got " + w + "x" + h + ")", w == size && h == size);
            bool opaque = part == AppIconSetter.Master || part == AppIconSetter.Ios || part == AppIconSetter.AdaptiveBg;
            if (opaque) Check(ship + " " + part + " has no alpha channel (colour type " + ct + ")", ct == 2);
            else Check(ship + " " + part + " has an alpha channel", ct == 6);
        }
    }

    static Texture2D Pixels(string path)
    {
        var tex = new Texture2D(2, 2, TextureFormat.RGBA32, false);
        tex.LoadImage(File.ReadAllBytes(path));
        return tex;
    }

    static void SafeZone(string ship)
    {
        var fg = Pixels(AppIconSetter.PathOf(ship, AppIconSetter.AdaptiveFg));
        int n = fg.width;
        float c = n / 2f, safe = n * 33f / 108f;  // 66dp circle of the 108dp layer
        Check("adaptive foreground corners are transparent",
              fg.GetPixel(0, 0).a == 0f && fg.GetPixel(n - 1, n - 1).a == 0f && fg.GetPixel(0, n - 1).a == 0f);
        Check("adaptive foreground centre is the opaque hull", fg.GetPixel(n / 2, n / 2).a > .95f);
        // everything (hull, glow AND exhaust) must sit in the safe circle, or the
        // launcher mask cuts it
        int outside = 0;
        for (int y = 0; y < n; y++)
            for (int x = 0; x < n; x++)
                if (fg.GetPixel(x, y).a > .2f && new Vector2(x + .5f - c, y + .5f - c).magnitude > safe) outside++;
        Check("ship + glow stay inside the 66dp safe circle (" + outside + " px outside)", outside == 0);
        Check("adaptive foreground has real art (not blank)", fg.GetPixel(n / 2, n / 2).a > .95f);
        Object.DestroyImmediate(fg);

        // opaque background layer: no pixel under the mask may be see-through
        var bg = Pixels(AppIconSetter.PathOf(ship, AppIconSetter.AdaptiveBg));
        bool opaque = true;
        foreach (var px in bg.GetPixels32()) if (px.a != 255) { opaque = false; break; }
        Check("adaptive background is fully opaque", opaque);
        Object.DestroyImmediate(bg);
    }

    static string PathOf(Texture2D t) { return t == null ? "(none)" : AssetDatabase.GetAssetPath(t); }

    static void PlayerSettingsUse(string ship)
    {
        var def = PlayerSettings.GetIcons(NamedBuildTarget.Unknown, IconKind.Any);
        Check(ship + ": default icon is the master",
              def.Length > 0 && PathOf(def[0]) == AppIconSetter.PathOf(ship, AppIconSetter.Master));

        bool adaptive = false, round = false, legacy = false, allSet = true;
        foreach (var kind in PlayerSettings.GetSupportedIconKinds(NamedBuildTarget.Android))
        {
            string k = AppIconSetter.AndroidKind(kind);
            foreach (var icon in PlayerSettings.GetPlatformIcons(NamedBuildTarget.Android, kind))
            {
                if (k == "Adaptive")
                {
                    adaptive = true;
                    allSet &= PathOf(icon.GetTexture(0)) == AppIconSetter.PathOf(ship, AppIconSetter.AdaptiveBg)
                              && PathOf(icon.GetTexture(1)) == AppIconSetter.PathOf(ship, AppIconSetter.AdaptiveFg);
                }
                else if (k == "Round")
                {
                    round = true;
                    allSet &= PathOf(icon.GetTexture()) == AppIconSetter.PathOf(ship, AppIconSetter.Round);
                }
                else
                {
                    legacy = true;
                    allSet &= PathOf(icon.GetTexture()) == AppIconSetter.PathOf(ship, AppIconSetter.Legacy);
                }
            }
        }
        Check(ship + ": Android has adaptive, round and legacy icon slots", adaptive && round && legacy);
        if (!(adaptive && round && legacy)) allSet = false;
        Check(ship + ": every Android slot uses the candidate (adaptive bg = layer 0, fg = layer 1)", allSet);


        int slots = 0;
        bool iosSet = true;
        foreach (var kind in PlayerSettings.GetSupportedIconKinds(NamedBuildTarget.iOS))
            foreach (var icon in PlayerSettings.GetPlatformIcons(NamedBuildTarget.iOS, kind))
            {
                slots++;
                iosSet &= PathOf(icon.GetTexture()) == AppIconSetter.PathOf(ship, AppIconSetter.Ios);
            }
        Check(ship + ": every iOS icon slot (" + slots + ") uses the alpha-free 1024", slots > 0 && iosSet);
        var importer = AssetImporter.GetAtPath(AppIconSetter.PathOf(ship, AppIconSetter.Ios)) as TextureImporter;
        Check(ship + ": iOS icon imports without alpha",
              importer != null && importer.alphaSource == TextureImporterAlphaSource.None);
    }
}
