using System.Collections.Generic;
using System.Diagnostics;
using System.Text;
using UnityEngine;
using Debug = UnityEngine.Debug;

// THE ATTACK BUDGET (docs/world-attacks-design.md FR6, implementation plan 0a).
//
// "Themed attacks replace attacks; they must not be harder." The dodge bot
// (DodgeBot: reaction .25 s, the ship's speed, aim locked at the tell) is
// rolled Rolls times per attack against the real game code
// (AttackBudgetScenarios) and its hit rate is PINNED here for every roster
// attacker, rail mine, elite and boss attack as it stood BEFORE any world got
// themed attacks. A themed attack that replaces an old one is measured the same
// way (same seed, so the same start positions) and must satisfy
//
//     rate(new) <= rate(old) * BudgetFactor + Slack
//
// (Slack: the rates are Monte Carlo over Rolls rolls; a 1-in-Rolls hit is noise.)
//
//   Pinned           id -> bot hits / rolls the attack showed itself in / the
//                    stand-still ghost's hits (information)
//   Themed           id of a new attack -> the id of the old attack it replaces
//                    (later phases add rows; AttackBudgetTest then checks them)
//   WithinBudget     the check, for any measured Result
//   Execute          harness sanity (deterministic, the bot beats a ghost, no
//                    hazards means no hits), spot checks of pinned entries, the
//                    catalogue is fully pinned or themed, every Themed row passes
//   Sweep            -executeMethod AttackBudgetTest.Sweep: measures EVERY
//                    attack and prints the pin table (PIN lines) to paste above
//
// Run: scripts/unity-batch.sh -executeMethod AllTests.RunSuites -suites AttackBudgetTest
public static class AttackBudgetTest
{
    static int fails;
    static void Check(string what, bool ok)
    {
        Debug.Log((ok ? "[ATKBUD] PASS  " : "[ATKBUD] FAIL  ") + what);
        if (!ok) fails++;
    }

    public static void Run() { TestHarness.Exit(Execute()); }

    // ---- the contract ------------------------------------------------------------
    public const int Rolls = 2000;          // seeded rolls per attack
    public const uint Seed = 1;
    public const float BudgetFactor = 1.15f;
    public const float Slack = .02f;        // absolute, on top of the factor: Monte Carlo noise at 2000 rolls (one standard error is <= 1.1 points)
    public const float MinAttackedShare = .5f;   // an attack that shows itself in under half the rolls is not measured, it is broken

    public struct Pin
    {
        public int hits, attacked, ghost;
        public Pin(int h, int a, int g) { hits = h; attacked = a; ghost = g; }
        public float Rate => attacked > 0 ? hits / (float)attacked : 0f;
    }

    // BASELINE: today's attacks (master f2d7e888 + the foundations), Rolls = 2000, Seed = 1.
    // Generated by Sweep (PIN lines); do not hand-edit.
    static readonly Dictionary<string, Pin> Pinned = new Dictionary<string, Pin>
    {
        { "roster:space_mine", new Pin(26, 2000, 1194) },   // 1.3 % bot, 59.7 % standing; shown in 2000/2000; Laser x1 volleys 2 cooldown 1.0 tell 0.9
        { "roster:space_big", new Pin(55, 2000, 521) },   // 2.8 % bot, 26.1 % standing; shown in 2000/2000; Shot x2 volleys 3 cooldown 2.6 tell 0.8
        { "roster:space_fighter_1", new Pin(0, 2000, 0) },   // 0.0 % bot, 0.0 % standing; shown in 2000/2000; Lunge x1 volleys 0 cooldown 2.0 tell 0.45
        { "roster:space_fighter_2", new Pin(0, 2000, 0) },   // 0.0 % bot, 0.0 % standing; shown in 2000/2000; Lunge x1 volleys 1 cooldown 1.6 tell 0.55
        { "roster:space_fighter_3", new Pin(83, 2000, 988) },   // 4.2 % bot, 49.4 % standing; shown in 2000/2000; Shot x2 volleys 3 cooldown 2.2 tell 0.6
        { "roster:space_fighter_4", new Pin(0, 2000, 2000) },   // 0.0 % bot, 100.0 % standing; shown in 2000/2000; Shot x1 volleys 4 cooldown 2.4 tell 0.9
        { "roster:space_alien", new Pin(11, 2000, 314) },   // 0.6 % bot, 15.7 % standing; shown in 2000/2000; Shot x1 volleys 2 cooldown 3.5 tell 0.55
        { "roster:frost_mine", new Pin(18, 2000, 1198) },   // 0.9 % bot, 59.9 % standing; shown in 2000/2000; Laser x1 volleys 2 cooldown 1.0 tell 0.9
        { "roster:frost_big", new Pin(83, 2000, 1086) },   // 4.2 % bot, 54.3 % standing; shown in 2000/2000; Shot x3 volleys 3 cooldown 3.2 tell 0.9
        { "roster:frost_fighter_1", new Pin(0, 2000, 0) },   // 0.0 % bot, 0.0 % standing; shown in 2000/2000; Lunge x1 volleys 0 cooldown 2.0 tell 0.55
        { "roster:frost_fighter_2", new Pin(0, 2000, 1998) },   // 0.0 % bot, 99.9 % standing; shown in 2000/2000; Shot x1 volleys 3 cooldown 2.0 tell 0.55
        { "roster:frost_fighter_3", new Pin(138, 2000, 911) },   // 6.9 % bot, 45.6 % standing; shown in 2000/2000; Shot x2 volleys 3 cooldown 2.2 tell 0.55
        { "roster:frost_fighter_4", new Pin(50, 2000, 548) },   // 2.5 % bot, 27.4 % standing; shown in 2000/2000; Shot x5 volleys 3 cooldown 3.4 tell 1.0
        { "roster:verdant_mine", new Pin(29, 2000, 1196) },   // 1.5 % bot, 59.8 % standing; shown in 2000/2000; Laser x1 volleys 2 cooldown 1.0 tell 1.0
        { "roster:verdant_big", new Pin(0, 2000, 0) },   // 0.0 % bot, 0.0 % standing; shown in 2000/2000; Lob x1 volleys 3 cooldown 3.5 tell 0.9
        { "roster:verdant_fighter_2", new Pin(0, 2000, 0) },   // 0.0 % bot, 0.0 % standing; shown in 2000/2000; Lunge x1 volleys 1 cooldown 2.0 tell 0.5
        { "roster:verdant_fighter_3", new Pin(0, 2000, 0) },   // 0.0 % bot, 0.0 % standing; shown in 2000/2000; Lunge x1 volleys 3 cooldown 1.3 tell 0.6
        { "roster:verdant_fighter_4", new Pin(184, 2000, 2000) },   // 9.2 % bot, 100.0 % standing; shown in 2000/2000; Shot x3 volleys 4 cooldown 2.6 tell 0.8
        { "roster:ember_mine", new Pin(60, 2000, 1197) },   // 3.0 % bot, 59.9 % standing; shown in 2000/2000; Laser x1 volleys 2 cooldown 1.0 tell 1.1
        { "roster:ember_big", new Pin(82, 2000, 770) },   // 4.1 % bot, 38.5 % standing; shown in 2000/2000; Shot x2 volleys 3 cooldown 3.6 tell 1.0
        { "roster:ember_fighter_1", new Pin(0, 2000, 0) },   // 0.0 % bot, 0.0 % standing; shown in 2000/2000; Lunge x1 volleys 0 cooldown 2.0 tell 0.45
        { "roster:ember_fighter_2", new Pin(19, 2000, 840) },   // 1.0 % bot, 42.0 % standing; shown in 2000/2000; Shot x1 volleys 4 cooldown 1.4 tell 0.5
        { "roster:ember_fighter_3", new Pin(14, 2000, 1989) },   // 0.7 % bot, 99.5 % standing; shown in 2000/2000; Shot x1 volleys 3 cooldown 1.8 tell 0.5
        { "roster:ember_fighter_4", new Pin(6, 2000, 173) },   // 0.3 % bot, 8.7 % standing; shown in 2000/2000; Ring x8 volleys 3 cooldown 3.8 tell 1.1
        { "roster:tide_mine", new Pin(32, 2000, 1188) },   // 1.6 % bot, 59.4 % standing; shown in 2000/2000; Laser x1 volleys 2 cooldown 1.0 tell 1.0
        { "roster:tide_big", new Pin(28, 2000, 475) },   // 1.4 % bot, 23.8 % standing; shown in 2000/2000; Shot x3 volleys 3 cooldown 3.6 tell 1.0
        { "roster:tide_fighter_1", new Pin(0, 2000, 0) },   // 0.0 % bot, 0.0 % standing; shown in 2000/2000; Lunge x1 volleys 0 cooldown 2.1 tell 0.45
        { "roster:tide_fighter_2", new Pin(26, 2000, 884) },   // 1.3 % bot, 44.2 % standing; shown in 2000/2000; Shot x1 volleys 4 cooldown 1.5 tell 0.5
        { "roster:tide_fighter_3", new Pin(0, 2000, 2000) },   // 0.0 % bot, 100.0 % standing; shown in 2000/2000; Shot x1 volleys 3 cooldown 2.0 tell 0.8
        { "roster:tide_fighter_4", new Pin(4, 2000, 162) },   // 0.2 % bot, 8.1 % standing; shown in 2000/2000; Ring x8 volleys 3 cooldown 3.8 tell 1.2
        { "elite:ember_elite_ash_wraith", new Pin(1940, 2000, 64) },   // 97.0 % bot, 3.2 % standing; shown in 2000/2000;
        { "elite:ember_elite_brass_vulture", new Pin(1098, 1654, 1098) },   // 66.4 % bot, 66.4 % standing; shown in 1654/2000;
        { "elite:ember_elite_cauterizer", new Pin(0, 2000, 706) },   // 0.0 % bot, 35.3 % standing; shown in 2000/2000;
        { "elite:ember_elite_coalrunner", new Pin(1938, 2000, 1992) },   // 96.9 % bot, 99.6 % standing; shown in 2000/2000;
        { "elite:ember_elite_kilnback", new Pin(2, 2000, 1199) },   // 0.1 % bot, 60.0 % standing; shown in 2000/2000;
        { "elite:ember_elite_sunstoke", new Pin(1542, 1743, 1542) },   // 88.5 % bot, 88.5 % standing; shown in 1743/2000;
        { "elite:frost_elite_cryo_siren", new Pin(98, 2000, 852) },   // 4.9 % bot, 42.6 % standing; shown in 2000/2000;
        { "elite:frost_elite_floe_harrower", new Pin(1550, 2000, 2000) },   // 77.5 % bot, 100.0 % standing; shown in 2000/2000;
        { "elite:frost_elite_glacier_tender", new Pin(0, 2000, 0) },   // 0.0 % bot, 0.0 % standing; shown in 2000/2000;
        { "elite:frost_elite_rimebreaker", new Pin(1665, 2000, 2000) },   // 83.3 % bot, 100.0 % standing; shown in 2000/2000;
        { "elite:frost_elite_whiteout_sentinel", new Pin(0, 2000, 0) },   // 0.0 % bot, 0.0 % standing; shown in 2000/2000;
        { "elite:space_elite_eventide_bastion", new Pin(202, 2000, 2000) },   // 10.1 % bot, 100.0 % standing; shown in 2000/2000;
        { "elite:space_elite_orbit_reaver", new Pin(0, 2000, 2000) },   // 0.0 % bot, 100.0 % standing; shown in 2000/2000;
        { "elite:space_elite_rift_lancer", new Pin(1802, 2000, 0) },   // 90.1 % bot, 0.0 % standing; shown in 2000/2000;
        { "elite:space_elite_singularity_hauler", new Pin(1717, 2000, 989) },   // 85.9 % bot, 49.5 % standing; shown in 2000/2000;
        { "elite:verdant_elite_resin_warden", new Pin(20, 2000, 515) },   // 1.0 % bot, 25.8 % standing; shown in 2000/2000;
        { "boss:Space:chin cannon", new Pin(97, 2000, 55) },   // 4.9 % bot, 2.8 % standing; shown in 2000/2000;
        { "boss:Space:core burst", new Pin(638, 2000, 2000) },   // 31.9 % bot, 100.0 % standing; shown in 2000/2000;
        { "boss:Space:pod lasers", new Pin(113, 2000, 1873) },   // 5.7 % bot, 93.7 % standing; shown in 2000/2000;
        { "boss:Frost:icicle spray", new Pin(1481, 2000, 2000) },   // 74.1 % bot, 100.0 % standing; shown in 2000/2000;
        { "boss:Frost:glare beams", new Pin(751, 2000, 2000) },   // 37.6 % bot, 100.0 % standing; shown in 2000/2000;
        { "boss:Frost:blowhole hail", new Pin(440, 2000, 1966) },   // 22.0 % bot, 98.3 % standing; shown in 2000/2000;
        { "boss:Verdant:stinger thorns", new Pin(31, 2000, 189) },   // 1.6 % bot, 9.5 % standing; shown in 2000/2000;
        { "boss:Verdant:spore bloom", new Pin(166, 2000, 1754) },   // 8.3 % bot, 87.7 % standing; shown in 2000/2000;
        { "boss:Verdant:acid cannons", new Pin(465, 2000, 2000) },   // 23.3 % bot, 100.0 % standing; shown in 2000/2000;
        { "boss:Ember:fire breath", new Pin(498, 2000, 2000) },   // 24.9 % bot, 100.0 % standing; shown in 2000/2000;
        { "boss:Ember:furnace slugs", new Pin(1161, 2000, 2000) },   // 58.1 % bot, 100.0 % standing; shown in 2000/2000;
        { "boss:Ember:brow laser", new Pin(1195, 2000, 1722) },   // 59.8 % bot, 86.1 % standing; shown in 2000/2000;
        // Iron Kraken placeholders (generic kinds, before its themed water attacks): the port fan is very hard (93.7 % bot) -- tune when themed.
        { "boss:Tide:port cluster", new Pin(1873, 2000, 1989) },   // 93.7 % bot, 99.5 % standing; shown in 2000/2000;
        { "boss:Tide:beak jet", new Pin(0, 2000, 1202) },   // 0.0 % bot, 60.1 % standing; shown in 2000/2000;
        { "boss:Tide:starboard cluster", new Pin(624, 2000, 1990) },   // 31.2 % bot, 99.5 % standing; shown in 2000/2000;
    };

    // New attack id -> the old attack id it replaces. Later phases add rows here
    // (e.g. { "roster:frost_big", "roster:frost_big" } once the Cold blast replaces the shard fan: same
    // id, the pin is the OLD attack's, Make() measures whatever the code now does).
    // A row whose id is unchanged means "this attack was re-themed in place; hold it to its own baseline".
    static readonly Dictionary<string, string> Themed = new Dictionary<string, string>
    {
        // plan phases 1c / 1d: the new area hazards on TEST-ONLY fixtures (AttackBudgetScenarios.ThemedFixtures); no world's table uses them yet
        { "themed:frost_cold_blast", "roster:frost_big" },          // Glacier Golem: the 3-shard fan -> the cold blast ring (volleys 3 -> 2)
        { "themed:ember_eruption", "roster:ember_fighter_3" },      // Brand: the aimed bolt -> an eruption of three columns
        { "themed:frost_icicle_drop", "roster:frost_fighter_2" },   // Icicle: the lance bolt -> an icicle drop on three lanes
        // plan phases 1a / 1b: the jet and the wave on TEST-ONLY fixtures too
        { "themed:ember_flame_jet", "roster:ember_fighter_3" },     // Brand: the aimed bolt -> a flamethrower cone (swept 10 deg); cooldown 1.8 -> 2.6, volleys 3 -> 2
        { "themed:frost_ray", "roster:frost_fighter_3" },           // Frost Kite: the splayed shard pair -> a thin frost ray
        { "themed:tide_pressure_jet", "roster:frost_fighter_2" },   // a pressure jet (water column) in place of the lance bolt
        { "themed:tide_surf_wave", "roster:ember_fighter_4" },      // Hammerhead: the ring of eight -> a surf wave with a 1.6 u gap; volleys 3 -> 2
        { "themed:space_scan_line", "roster:space_fighter_3" },     // Void Archon's scan line (a thin neon wave): a NEW boss attack, held to Twin Claw's (the middle Space fighter) rate
    };

    public static bool WithinBudget(string id, DodgeBot.Result r, out string why)
    {
        string old;
        if (!Themed.TryGetValue(id, out old)) old = id;
        Pin p;
        if (!Pinned.TryGetValue(old, out p)) { why = "no baseline pinned for " + old; return false; }
        float limit = p.Rate * BudgetFactor + Slack;
        why = id + ": bot hit rate " + r.HitRate.ToString("P1") + " (" + r.hits + "/" + r.attacked + ") vs baseline " + old + " " +
              p.Rate.ToString("P1") + " (" + p.hits + "/" + p.attacked + "), limit " + limit.ToString("P1");
        return r.HitRate <= limit && r.AttackedShare >= MinAttackedShare;
    }

    // Measure one attack the way the pins were measured.
    public static DodgeBot.Result Measure(string id, int rolls = Rolls)
    {
        AttackBudgetScenarios.Reset();
        try { return DodgeBot.Run(AttackBudgetScenarios.Make(id), rolls, Seed); }
        finally { AttackBudgetScenarios.Cleanup(); }
    }

    // ---- the suite -----------------------------------------------------------------

    // A spread to re-measure every run: one attacker per world and kind, a mine, an elite, a boss attack.
    static readonly string[] SpotChecks =
    {
        "roster:space_fighter_4", "roster:frost_fighter_2", "roster:verdant_fighter_4", "roster:ember_fighter_3", "roster:verdant_big",
    };

    public static int Execute()
    {
        fails = 0;
        using (new TestHarness.Sandbox())
        {
            try
            {
                Harness();
                Catalogue();
                SpotChecksHold();
                ThemedRowsPass();
            }
            finally { AttackBudgetScenarios.Cleanup(); }
        }
        Debug.Log("[ATKBUD] failures: " + fails);
        return fails;
    }

    static void Harness()
    {
        // 1. deterministic: the same attack twice, the same numbers
        var a = Measure("roster:space_fighter_4", 60);
        var b = Measure("roster:space_fighter_4", 60);
        Check("the harness is deterministic (" + a.hits + "/" + a.attacked + " twice: " + b.hits + "/" + b.attacked + ")",
              a.hits == b.hits && a.attacked == b.attacked && a.ghostHits == b.ghostHits && a.attacked > 0);
        // 2. the bot dodges: against a ghost that stands still, an aimed attack hits far more often
        Check("the bot beats a ghost that never moves (bot " + a.hits + " vs ghost " + a.ghostHits + " of " + a.attacked + ")",
              a.ghostHits >= 10 && a.hits < a.ghostHits);
        // 3. nothing to dodge, nothing hit: a rock never attacks, so the bot is never hit and the attack never shows
        var rock = new Quiet();
        AttackBudgetScenarios.Reset();
        var q = DodgeBot.Run(rock, 20, Seed);
        Check("a hazard-free world scores no hits and no attacks (" + q.hits + "/" + q.attacked + ")", q.hits == 0 && q.attacked == 0 && q.ghostHits == 0);
        // 4. a hazard that cannot be avoided is scored: a wall across the lane the bot cannot leave
        var wall = new Wall();
        var w = DodgeBot.Run(wall, 20, Seed);
        Check("an unavoidable hazard scores a hit in every roll (" + w.hits + "/" + w.attacked + ")", w.attacked == 20 && w.hits == 20);
        AttackBudgetScenarios.Cleanup();
    }

    sealed class Quiet : DodgeBot.IScenario
    {
        public string Name => "quiet";
        public float MaxSeconds => 1f;
        public bool Telling => false;
        public bool Attacked => false;
        public bool Done => false;
        public Transform Begin(System.Random rng, Vector2 start) { return AttackBudgetScenarios.EnsureShip(start); }
        public void Step(float dt) { }
        public void Collect(List<DodgeBot.Hz> into) { }
        public void End() { }
    }

    // A hazard bigger than the playfield, live for the whole roll: no flight escapes it.
    sealed class Wall : DodgeBot.IScenario
    {
        public string Name => "wall";
        public float MaxSeconds => 1f;
        public bool Telling => false;
        public bool Attacked => true;
        public bool Done => false;
        public Transform Begin(System.Random rng, Vector2 start) { return AttackBudgetScenarios.EnsureShip(start); }
        public void Step(float dt) { }
        public void Collect(List<DodgeBot.Hz> into)
        {
            into.Add(DodgeBot.Hz.Circle(2, new Vector2(0f, -2.5f), 9f, 0f, 99f));
        }
        public void End() { }
    }

    static void Catalogue()
    {
        var missing = new List<string>();
        int n = 0;
        foreach (var id in AttackBudgetScenarios.AllIds())
        {
            n++;
            if (!Pinned.ContainsKey(id) && !Themed.ContainsKey(id)) missing.Add(id);
        }
        Check("every roster attacker, mine, elite and boss attack has a pinned baseline or a Themed row (" + n + " attacks; unpinned: " +
              string.Join(", ", missing) + ")", missing.Count == 0 && n >= 40);
        var stale = new List<string>();
        var live = new HashSet<string>(AttackBudgetScenarios.AllIds());
        foreach (var k in Pinned.Keys) if (!live.Contains(k) && !Themed.ContainsValue(k)) stale.Add(k);
        Check("every pin still names an attack in the game, or one a Themed row replaced (stale: " + string.Join(", ", stale) + ")", stale.Count == 0);
    }

    static void SpotChecksHold()
    {
        foreach (var id in SpotChecks)
        {
            Pin p;
            if (!Pinned.TryGetValue(id, out p)) { Check(id + ": pinned", false); continue; }
            var r = Measure(id);
            // (a few rolls can differ run to run: the world's clock and the brains' drift directions carry a little state between
            // attacks in one editor process; within a point and a half is the same measurement)
            int tol = Mathf.CeilToInt(Rolls * .015f);
            Check(id + ": today's attack still measures its pin (" + r.hits + "/" + r.attacked + " ghost " + r.ghostHits + " vs " + p.hits + "/" + p.attacked + " ghost " + p.ghost + ", tolerance " + tol + ")",
                  Mathf.Abs(r.hits - p.hits) <= tol && Mathf.Abs(r.attacked - p.attacked) <= tol && Mathf.Abs(r.ghostHits - p.ghost) <= tol);
        }
    }

    static void ThemedRowsPass()
    {
        foreach (var kv in Themed)
        {
            var r = Measure(kv.Key);
            string why;
            bool ok = WithinBudget(kv.Key, r, out why);
            Check("themed attack within the budget: " + why, ok);
        }
    }

    // ---- the sweep: measure everything, print the table ---------------------------------

    // -executeMethod AttackBudgetTest.Sweep [-rolls N] [-only substring]
    // -executeMethod AttackBudgetTest.SweepThemed [-rolls N] [-only substring] [-trace]: the same for the themed fixtures (they are not
    // attacks of the game, so Sweep does not list them): hit rate, standing-still rate and the budget verdict against the pinned attack.
    public static void SweepThemed()
    {
        fails = 0;
        int rolls = Rolls;
        string only = null;
        var args = System.Environment.GetCommandLineArgs();
        for (int i = 0; i < args.Length - 1; i++)
        {
            if (args[i] == "-rolls") int.TryParse(args[i + 1], out rolls);
            if (args[i] == "-only") only = args[i + 1];
        }
        for (int i = 0; i < args.Length; i++) if (args[i] == "-trace") DodgeBot.Trace = true;
        try
        {
            foreach (var kv in Themed)
            {
                if (only != null && !kv.Key.Contains(only)) continue;
                var r = Measure(kv.Key, rolls);
                string why;
                bool ok = WithinBudget(kv.Key, r, out why);
                Debug.Log("[ATKBUD] THEMED " + (ok ? "ok   " : "OVER ") + kv.Key + ": bot " + r.HitRate.ToString("P1") + " (" + r.hits + "/" + r.attacked + "), standing still " + r.GhostRate.ToString("P1") +
                          ", shown in " + r.attacked + "/" + r.rolls + "; " + AttackBudgetScenarios.Shape(kv.Key) + " -- " + why);
            }
        }
        finally { AttackBudgetScenarios.Cleanup(); }
        TestHarness.Exit(0);
    }

    public static void Sweep()
    {
        fails = 0;
        int rolls = Rolls;
        string only = null;
        var args = System.Environment.GetCommandLineArgs();
        for (int i = 0; i < args.Length - 1; i++)
        {
            if (args[i] == "-rolls") int.TryParse(args[i + 1], out rolls);
            if (args[i] == "-only") only = args[i + 1];
        }
        for (int i = 0; i < args.Length; i++) if (args[i] == "-trace") DodgeBot.Trace = true;
        var sw = Stopwatch.StartNew();
        var sb = new StringBuilder();
        int bad = 0;
        try
        {
            foreach (var id in AttackBudgetScenarios.AllIds())
            {
                if (only != null && !id.Contains(only)) continue;
                var t = Stopwatch.StartNew();
                var r = Measure(id, rolls);
                string line = "        { \"" + id + "\", new Pin(" + r.hits + ", " + r.attacked + ", " + r.ghostHits + ") },   // " +
                              r.HitRate.ToString("P1") + " bot, " + r.GhostRate.ToString("P1") + " standing; shown in " + r.attacked + "/" + r.rolls +
                              "; " + AttackBudgetScenarios.Shape(id);
                if (r.AttackedShare < MinAttackedShare) { line += "  <-- SHOWS ITSELF IN UNDER HALF THE ROLLS"; bad++; }
                Debug.Log("[ATKBUD] PIN " + line.Trim() + "  (" + t.Elapsed.TotalSeconds.ToString("0.0") + " s)");
                sb.AppendLine(line);
            }
        }
        finally { AttackBudgetScenarios.Cleanup(); }
        Debug.Log("[ATKBUD] sweep done in " + sw.Elapsed.TotalSeconds.ToString("0") + " s; attacks that barely show: " + bad);
        TestHarness.Exit(0);
    }
}
