using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

// Builds the space dock when shopS6 loads.
//
// The scene keeps only its camera, starfield, HUD canvases and the UIManager
// scripts; the dock (berths, ships, popup) is generated by SpaceDock so that
// growing the roster stays a code change. Runs from sceneLoaded, before any
// Start() in the scene.
public static class ShopSceneExtender
{
    public static void Build()
    {
        var canvas = SceneUtil.FindAny("Canvas");

        // This canvas was authored inactive, which made the only currency
        // readout disappear even though shopingShips was correctly updating it.
        var dustCanvas = SceneUtil.FindAny("StarDustCanvas");
        if (dustCanvas != null) dustCanvas.SetActive(true);
        EnsureInstruction(canvas);
        SpaceDock.StyleChrome(canvas);
        SpaceDock.Build();
    }

    static void EnsureInstruction(GameObject canvas)
    {
        if (canvas == null) return;
        var go = SceneUtil.FindAny("~DockInstruction");
        if (go == null)
        {
            go = new GameObject("~DockInstruction", typeof(Text));
            go.transform.SetParent(canvas.transform, false);
        }
        var label = go.GetComponent<Text>();
        var font = DockArt.FindSceneFont();
        label.font = font != null ? font : Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
        label.alignment = TextAnchor.MiddleCenter;
        label.raycastTarget = false;
        var rt = label.rectTransform;
        rt.anchorMin = rt.anchorMax = new Vector2(0.5f, 1f);
        rt.pivot = new Vector2(0.5f, 1f);
    }
}

// Register once at process start and build before the scene's Start()
// methods run.
public static class ShopSceneBootstrap
{
    [RuntimeInitializeOnLoadMethod]
    static void Init()
    {
        SceneManager.sceneLoaded -= OnSceneLoaded;
        SceneManager.sceneLoaded += OnSceneLoaded;
        // Also support opening shopS6 directly in the editor or as a build's
        // first scene; AfterSceneLoad registration would otherwise miss it.
        if (SceneManager.GetActiveScene().name == "shopS6")
            ShopSceneExtender.Build();
    }

    static void OnSceneLoaded(Scene scene, LoadSceneMode mode)
    {
        if (scene.name == "shopS6") ShopSceneExtender.Build();
    }
}
