"""Builds every player hull flipbook and the data the game reads.

    python3 build.py            # svg -> png (resvg) -> sheets -> C# tables
    python3 build.py --svg-only

Per ship it writes ../<Key>.png, a sheet of 256 px cells (128 u canvas at 2x):

    rows    = damage state (0 intact, 1 damaged, 2 critical), top to bottom
    columns = IDLE drawings 0..5, bank left, bank right, hit flash

and patches the generated blocks of Scripts/Ship/ShipHullArt.cs (sprite rect
and pixels-per-unit per ship) and Scripts/Ship/ShipNozzles.cs (nozzle points
re-measured from the rendered rest frame).

The rect is the union of the art over every cell, so all frames share one
rect and pivot (the bob and the bank happen inside it). Pixels-per-unit is
chosen so the rect has the old sprite's world size: everything sized off
sprite.bounds (collider, shield, dock, exhaust) keeps its numbers.
"""
import os
import re
import subprocess
import sys

from PIL import Image

from hullkit import *  # noqa: F401,F403
import damage
from ships import BUILDERS, HUES, OLD_RECTS, ORDER, SPINNERS

OUT_DIR = os.path.abspath(os.path.join(HERE, ".."))
BUILD = os.path.join(HERE, "build")
SCRIPTS = os.path.join(REPO, "Pause/Assets/Scripts/Ship")
ZOOM = 2
CELL = 128 * ZOOM

# ------------------------------------------------------------ frame table --
# Idle drawings (columns 0-5) and the order/holds the game plays them in
# (24 fps ticks, on 2s and 3s, resting on the held key pose).
IDLE = [
    Pose(dy=0.0, lights=True),                 # 0 key pose, lights on
    Pose(dy=-2.0, lights=True),                # 1 bob up
    Pose(dy=-2.0, lights=False),               # 2 up, running lights blink off
    Pose(dy=0.0, lights=True, glint=0.15),     # 3 canopy glint enters
    Pose(dy=0.0, lights=False, glint=0.75),    # 4 glint sweeps off, lights blink
    Pose(dy=2.0, lights=True),                 # 5 bob down
]
IDLE_SEQUENCE = [(0, 6), (1, 3), (2, 3), (1, 3), (0, 3), (5, 3), (0, 4), (3, 2), (4, 2), (0, 3), (5, 3)]
BANK_L, BANK_R, HIT = 6, 7, 8
COLUMNS = 9
STATES = 3


def poses(spinner):
    cols = list(IDLE)
    cols.append(Pose(bank=0.0 if spinner else -1.0))
    cols.append(Pose(bank=0.0 if spinner else 1.0))
    cols.append(Pose(flash=True))
    return cols


# -------------------------------------------------------------- fitting --
def _all_points(ship):
    for fm in ship.forms:
        yield from fm.outline


def fit(ship, aspect):
    """Scale + stretch the design to the canvas and to the old aspect (w/h)."""
    xs = [p[0] for p in _all_points(ship)]
    ys = [p[1] for p in _all_points(ship)]
    gx0, gx1, gy0, gy1 = min(xs), max(xs), min(ys), max(ys)
    gw, gh = gx1 - gx0, gy1 - gy0
    ink = 2 * OUTER
    longest = 110.0
    if aspect >= 1:
        sx = longest / gw
        sy = ((longest + ink) / aspect - ink) / gh
    else:
        sy = longest / gh
        sx = ((longest + ink) * aspect - ink) / gw
    cx, cy = (gx0 + gx1) / 2, (gy0 + gy1) / 2

    def m(pts):
        return [(64 + (x - cx) * sx, 64 + (y - cy) * sy) for x, y in pts]

    for fm in ship.forms:
        fm.outline = m(fm.outline)
        fm.shade = [m(s) for s in fm.shade]
        fm.details = [(m(p), r, w) for p, r, w in fm.details]
        fm.lines = [(m(p), w) for p, w in fm.lines]
    if ship.canopy:
        ship.canopy = m(ship.canopy)
    ship.lights = [(*m([(x, y)])[0], r, role) for x, y, r, role in ship.lights]
    ship.nozzles = [(*m([(x, y)])[0], w * sx, k) for x, y, w, k in ship.nozzles]
    ship.stripes = [(m(p), r) for p, r in ship.stripes]
    ship.fit = m
    return ship


def load(key):
    w, h = OLD_RECTS[key]
    ship = fit(BUILDERS[key](), w / h)
    return damage.attach(ship, ship.fit)


# ------------------------------------------------------------- rendering --
def svg_for(ship, pose, uid):
    body, defs = render(ship, HUES[ship.key], pose, uid)
    comment = (f"{ship.key}: damage {pose.damage}, dy {pose.dy}, bank {pose.bank}, "
               f"lights {pose.lights}, glint {pose.glint}, flash {pose.flash}. "
               f"Generated by build.py; idle ticks {IDLE_SEQUENCE}")
    return svg(128, 128, body, comment, defs)


def build_ship(key, render_png=True):
    ship = load(key)
    cols = poses(key in SPINNERS)
    os.makedirs(BUILD, exist_ok=True)
    cells = {}
    for state in range(STATES):
        for c, base in enumerate(cols):
            pose = Pose(base.dy, base.bank, base.lights, base.glint, base.flash, state)
            name = f"{key}_{state}_{c}"
            path = os.path.join(BUILD, name + ".svg")
            with open(path, "w") as fh:
                fh.write(svg_for(ship, pose, f"k{state}{c}"))
            png = os.path.join(BUILD, name + ".png")
            if render_png:
                subprocess.run(["resvg", "--zoom", str(ZOOM), path, png], check=True)
            cells[(state, c)] = png
    return ship, cells


def compose(key, ship, cells):
    sheet = Image.new("RGBA", (CELL * COLUMNS, CELL * STATES), (0, 0, 0, 0))
    union = None
    for (state, c), png in cells.items():
        im = Image.open(png).convert("RGBA")
        assert im.size == (CELL, CELL), im.size
        # clean alpha: drop the faintest AA dust (< 4/255) so nothing
        # half-invisible survives outside the ink line
        a = im.getchannel("A").point(lambda v: 0 if v < 4 else v)
        im.putalpha(a)
        sheet.alpha_composite(im, (c * CELL, state * CELL))
        bb = im.getbbox()
        union = bb if union is None else (min(union[0], bb[0]), min(union[1], bb[1]),
                                          max(union[2], bb[2]), max(union[3], bb[3]))
    x0, y0, x1, y1 = union
    x0, y0, x1, y1 = max(0, x0 - 1), max(0, y0 - 1), min(CELL, x1 + 1), min(CELL, y1 + 1)
    # make the rect's aspect exactly the old one (pad the short side, centred)
    ow, oh = OLD_RECTS[key]
    w, h = x1 - x0, y1 - y0
    if w / h < ow / oh:
        want = round(h * ow / oh)
        pad = want - w
        x0 -= pad // 2
        x1 = x0 + want
    else:
        want = round(w * oh / ow)
        pad = want - h
        y0 -= pad // 2
        y1 = y0 + want
    assert x0 >= 0 and y0 >= 0 and x1 <= CELL and y1 <= CELL, (key, x0, y0, x1, y1)
    check_alpha(key, sheet)
    check_emitters(ship, sheet)
    sheet.save(os.path.join(OUT_DIR, key + ".png"), optimize=True)
    rest = sheet.crop((0, 0, CELL, CELL))
    return (x0, y0, x1, y1), rest


def measure_nozzles(ship, rect, rest):
    """Each nozzle's exit, in sprite-rect pixels (x from left, y from bottom),
    snapped to the last painted row of its own column in the rest frame."""
    x0, y0, x1, y1 = rect
    alpha = rest.getchannel("A")
    out = []
    for x, y, w, k in ship.nozzles:
        px = int(round(x * ZOOM))
        py = int(round(y * ZOOM))
        if w > 0:
            # walk down from the nozzle's slot to the last opaque pixel
            while py + 1 < CELL and alpha.getpixel((px, py + 1)) > 200:
                py += 1
            py -= 2   # sit just inside the lip, on paint
        assert alpha.getpixel((px, py)) > 200, (ship.key, px, py)
        rx = px + 0.5 - x0
        ry = y1 - (py + 0.5)
        out.append((rx, ry, k))
    return out


def posed(u, v, col, spinner):
    """A canvas point as drawn in column `col` (ShipDamageTable.Posed)."""
    pose = poses(spinner)[col]
    (x, y), = warp([(u, v)], pose)
    return x, y


def check_emitters(ship, sheet):
    """Every damage emitter sits on painted pixels in the rest frame and in
    every pose it can be drawn in, at every state it is live."""
    alpha = sheet.getchannel("A")
    for state in (1, 2):
        for kind, u, v in ship.emitters[state]:
            for col in range(COLUMNS):
                x, y = posed(u, v, col, ship.key in SPINNERS)
                for s in range(state, STATES):
                    a = alpha.getpixel((int(col * CELL + x * ZOOM), int(s * CELL + y * ZOOM)))
                    assert a > 200, (ship.key, kind, u, v, col, s, a)


def check_alpha(key, sheet):
    """Damage is drawn inside the outline: rows 1-2 have row 0's exact alpha."""
    from PIL import ImageChops
    a = sheet.getchannel("A")
    rest = a.crop((0, 0, CELL * COLUMNS, CELL))
    for s in range(1, STATES):
        bad = ImageChops.difference(rest, a.crop((0, s * CELL, CELL * COLUMNS, (s + 1) * CELL))).getbbox()
        assert bad is None, f"{key}: damage state {s} alpha differs from intact at {bad}"


KIND_CS = {"sparks": "Sparks", "arc": "Arc", "smoke": "Smoke", "flame": "Flame", "leak": "Leak"}


def emitter_rows():
    rows = []
    for i, key in enumerate(ORDER, start=1):
        ship = load(key)
        parts = [f"E({st}, {KIND_CS[k]}, {u:.1f}f, {v:.1f}f)" for st in (1, 2) for k, u, v in ship.emitters[st]]
        c1, c2 = damage.CONCEPTS[key]
        rows.append(f"        // {i:2d} {key}: 1) {c1}; 2) {c2}\n"
                    f"        new[] {{ {', '.join(parts)} }},\n")
    return "".join(rows)


# ------------------------------------------------------------ C# patching --
def patch(path, begin, end, text):
    with open(path) as fh:
        src = fh.read()
    pat = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.S)
    assert pat.search(src), (path, begin)
    src = pat.sub(lambda _m: begin + "\n" + text + "        " + end, src)
    with open(path, "w") as fh:
        fh.write(src)


def num(v):
    s = f"{v:.1f}"
    return s + "f"


def main():
    only_svg = "--svg-only" in sys.argv
    keys = [k for k in ORDER if not any(a for a in sys.argv[1:] if not a.startswith("--"))
            or k in sys.argv[1:]]
    rects, nozzles = {}, {}
    for key in keys:
        ship, cells = build_ship(key, not only_svg)
        if only_svg:
            continue
        rect, rest = compose(key, ship, cells)
        rects[key] = rect
        nozzles[key] = measure_nozzles(ship, rect, rest)
        x0, y0, x1, y1 = rect
        print(f"{key:12s} rect {x1 - x0}x{y1 - y0} at ({x0},{y0}) nozzles {nozzles[key]}")
    if only_svg or len(keys) != len(ORDER) or "--no-patch" in sys.argv:
        return

    rows, nrows = [], []
    for i, key in enumerate(ORDER, start=1):
        x0, y0, x1, y1 = rects[key]
        w, h = x1 - x0, y1 - y0
        ow, oh = OLD_RECTS[key]
        ppu = w / (ow / 100.0)
        # Unity rects are bottom-up inside a cell
        rows.append(f'        /* {i:2d} {key:12s} */ new HullRect({x0}, {CELL - y1}, {w}, {h}, {ppu:.4f}f, "{HUES[key][0]}", "{HUES[key][1]}", "{HUES[key][2]}"),\n')
        parts = []
        for rx, ry, k in nozzles[key]:
            parts.append(f"N({num(rx)}, {num(ry)}" + ("" if k == 1.0 else (", Twin" if k == TWIN_K else f", {k}f")) + ")")
        nrows.append(f"        /* {i:2d} {key:12s} {w}x{h} */ new[] {{ {', '.join(parts)} }},\n")
    patch(os.path.join(SCRIPTS, "ShipHullArt.cs"), "// BEGIN GENERATED RECTS", "// END GENERATED RECTS",
          "".join(rows))
    patch(os.path.join(SCRIPTS, "ShipNozzles.cs"), "// BEGIN GENERATED NOZZLES", "// END GENERATED NOZZLES",
          "".join(nrows))
    patch(os.path.join(SCRIPTS, "ShipDamageTable.cs"), "// BEGIN GENERATED EMITTERS", "// END GENERATED EMITTERS",
          emitter_rows())
    print("patched ShipHullArt.cs, ShipNozzles.cs and ShipDamageTable.cs")


TWIN_K = 0.72

if __name__ == "__main__":
    main()
