"""Builds every purchasable hull skin (skins.py) through the hull pipeline.

    python3 build_skins.py               # all ships, all skins
    python3 build_skins.py NeonComet     # one ship (no C# patch)
    python3 build_skins.py --verify-stock

Per ship and non-stock skin it renders the same 27 frames build.py does
(3 damage states x idle 0-5, bank L/R, hit) with the skin's colours and
writes the sheet as PNG bytes:

    ../../Skins/<Key>_<Skin>.bytes     (Resources/ShipArt/Skins, a TextAsset)

The game decodes a sheet only when that skin is shown (ShipHullArt), so the
build carries compact PNGs instead of 60 GPU textures. Each sheet must have
exactly the stock sheet's alpha -- a skin changes colours, never the shape --
which this script asserts. It then patches the generated table in
Scripts/Ship/ShipSkins.cs (names, kinds, colours).

--verify-stock re-renders every stock sheet through the skin-aware renderer
and checks it is pixel-identical to the committed ../<Key>.png.
"""
import io
import os
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor

from PIL import Image, ImageChops

from build import BUILD, CELL, COLUMNS, OUT_DIR, SCRIPTS, STATES, load, patch, poses
from hullkit import Pose, render, svg
from ships import ORDER, SPINNERS
from skins import SKINS, livery

SKIN_DIR = os.path.abspath(os.path.join(OUT_DIR, "..", "Skins"))
SKIN_BUILD = os.path.join(BUILD, "skins")
ZOOM = 2


def svg_for(ship, skin, pose, uid):
    liv = (livery(ship, skin.pattern), skin.pattern_hue) if skin.pattern else None
    body, defs = render(ship, skin.hue, pose, uid, livery=liv, trim=skin.trim)
    comment = (f"{ship.key} skin {skin.name}: damage {pose.damage}, dy {pose.dy}, bank {pose.bank}, "
               f"lights {pose.lights}, glint {pose.glint}, flash {pose.flash}. Generated by build_skins.py")
    return svg(128, 128, body, comment, defs)


def render_cells(key, index):
    ship = load(key)
    skin = SKINS[key][index]
    cols = poses(key in SPINNERS)
    os.makedirs(SKIN_BUILD, exist_ok=True)
    jobs = []
    for state in range(STATES):
        for c, base in enumerate(cols):
            pose = Pose(base.dy, base.bank, base.lights, base.glint, base.flash, state)
            name = f"{key}_{skin.name}_{state}_{c}"
            path = os.path.join(SKIN_BUILD, name + ".svg")
            with open(path, "w") as fh:
                fh.write(svg_for(ship, skin, pose, f"k{state}{c}"))
            jobs.append(((state, c), path, os.path.join(SKIN_BUILD, name + ".png")))
    with ThreadPoolExecutor(8) as pool:
        list(pool.map(lambda j: subprocess.run(["resvg", "--zoom", str(ZOOM), j[1], j[2]], check=True), jobs))
    return skin, {k: png for k, _, png in jobs}


def compose(cells):
    """The sheet, composed and alpha-cleaned exactly like build.compose."""
    sheet = Image.new("RGBA", (CELL * COLUMNS, CELL * STATES), (0, 0, 0, 0))
    for (state, c), png in cells.items():
        im = Image.open(png).convert("RGBA")
        assert im.size == (CELL, CELL), im.size
        a = im.getchannel("A").point(lambda v: 0 if v < 4 else v)
        im.putalpha(a)
        sheet.alpha_composite(im, (c * CELL, state * CELL))
    return sheet


def stock(key):
    return Image.open(os.path.join(OUT_DIR, key + ".png")).convert("RGBA")


def png_bytes(sheet):
    buf = io.BytesIO()
    sheet.save(buf, "PNG", optimize=True)
    return buf.getvalue()


def build_skin(key, index):
    skin, cells = render_cells(key, index)
    sheet = compose(cells)
    diff = ImageChops.difference(sheet.getchannel("A"), stock(key).getchannel("A")).getbbox()
    assert diff is None, f"{key} {skin.name}: alpha differs from the stock sheet at {diff}"
    data = png_bytes(sheet)
    os.makedirs(SKIN_DIR, exist_ok=True)
    with open(os.path.join(SKIN_DIR, f"{key}_{skin.name}.bytes"), "wb") as fh:
        fh.write(data)
    return skin, len(data)


def verify_stock():
    bad = 0
    for key in ORDER:
        _, cells = render_cells(key, 0)
        diff = ImageChops.difference(compose(cells), stock(key)).getbbox()
        print(f"{key:12s} stock re-render {'identical' if diff is None else 'DIFFERS at ' + str(diff)}")
        bad += diff is not None
    return bad


def cs_table():
    rows = []
    for i, key in enumerate(ORDER, start=1):
        parts = []
        for skin in SKINS[key]:
            b, s, h = skin.hue
            if skin.pattern:
                pb, ps, ph = skin.pattern_hue
                parts.append(f'S("{skin.name}", ShipSkinKind.{skin.kind}, "{b}", "{s}", "{h}", '
                             f'"{skin.pattern}", "{pb}", "{ps}", "{ph}")')
            else:
                parts.append(f'S("{skin.name}", ShipSkinKind.{skin.kind}, "{b}", "{s}", "{h}")')
        rows.append(f"        /* {i:2d} {key:12s} */ new[] {{\n            "
                    + ",\n            ".join(parts) + " },\n")
    return "".join(rows)


def main():
    if "--verify-stock" in sys.argv:
        sys.exit(1 if verify_stock() else 0)
    only = [a for a in sys.argv[1:] if not a.startswith("--")]
    keys = [k for k in ORDER if not only or k in only]
    total = 0
    for key in keys:
        for index in range(1, len(SKINS[key])):
            skin, size = build_skin(key, index)
            total += size
            print(f"{key:12s} {index} {skin.name:10s} {size / 1024:7.1f} KB")
    print(f"skin sheets: {total / 1024 / 1024:.2f} MB")
    if not only:
        patch(os.path.join(SCRIPTS, "ShipSkins.cs"), "// BEGIN GENERATED SKINS", "// END GENERATED SKINS",
              cs_table())
        print("patched ShipSkins.cs")


if __name__ == "__main__":
    main()
