using System;
using UnityEngine;

public enum ShipSkinKind { Stock, Palette, Special }

// One colourway of one hull. Colours are the hull ("hull"-tone forms) base,
// its one shadow and its one highlight; a special also has a livery pattern
// painted in a second colour (accent*). Friendly red (lights, red trim) is
// the same on every skin and is not listed.
public struct ShipSkin
{
    public string name;               // "Stock", "Night", "Kaneda", ...
    public ShipSkinKind kind;
    public string hue, hueShadow, hueHighlight;
    public string pattern;            // null, or racing / chevrons / diagonal / split
    public string accent, accentShadow, accentHighlight;

    public Color primary { get { return ShipSkins.Parse(hue); } }
    public Color shadow { get { return ShipSkins.Parse(hueShadow); } }
    public Color highlight { get { return ShipSkins.Parse(hueHighlight); } }
    // The livery colour of a special; the primary for every other skin.
    public Color accentColor { get { return ShipSkins.Parse(accent ?? hue); } }
    public string DisplayName { get { return (name ?? "").ToUpperInvariant(); } }
}

// Purchasable hull colourways ("skins"): the table, the economy and the
// saved state. The art is ShipHullArt's (one sheet per ship and skin,
// generated by Art/Resources/ShipArt/Hulls/src~/build_skins.py).
//
// Every ship has PerShip skins: 0 is Stock (its own hue, free and always
// owned), 1-3 are palette swaps, 4 is the ship's special livery.
//
// Saved (PlayerPrefs, synced by ProgressSnapshot):
//   shipSkin<id>        the equipped skin index (absent = 0, Stock)
//   skinOwned<id>_<n>   1 when skin n (1..PerShip-1) of ship id was bought
//
// Developer mode (DeveloperUnlocks) shows every skin as owned without
// writing any of those keys, the way the codex shows every entry: ownership
// is answered at read time, and an equip while it is on goes to
// developerShipSkin<id>, which is ignored (and cleared) once it is off. So
// switching it off leaves the real choice and ownership exactly as they were.
//
// The dock can preview a skin on the hull before it is bought (Preview);
// Shown(id) is what every renderer of the ship uses.
public static class ShipSkins
{
    public const int PerShip = 5;
    public const int Stock = 0;
    public const int Special = PerShip - 1;

    public const string EquippedKeyPrefix = "shipSkin";
    public const string OwnedKeyPrefix = "skinOwned";
    public const string DeveloperEquippedPrefix = "developerShipSkin";

    // ---------------------------------------------------------- economy
    // The one config table: price in star dust by kind (Stock, Palette, Special).
    public static readonly float[] KindPrices = { 0f, 300f, 750f };

    public static float PriceOf(ShipSkinKind kind) { return KindPrices[(int)kind]; }

    public static float PriceOf(int id, int skin)
    {
        return Has(id, skin) ? PriceOf(Get(id, skin).kind) : 0f;
    }

    // Raised with the ship id when its equipped or previewed skin changes.
    public static event Action<int> Changed;

    // ---------------------------------------------------------- table

    static ShipSkin S(string name, ShipSkinKind kind, string hue, string shadow, string highlight,
                      string pattern = null, string accent = null, string accentShadow = null,
                      string accentHighlight = null)
    {
        return new ShipSkin
        {
            name = name, kind = kind, hue = hue, hueShadow = shadow, hueHighlight = highlight,
            pattern = pattern, accent = accent, accentShadow = accentShadow, accentHighlight = accentHighlight,
        };
    }

    // By ship id (ShipId), then skin index.
    static readonly ShipSkin[][] table =
    {
        null,
        // BEGIN GENERATED SKINS
        /*  1 NeonComet    */ new[] {
            S("Stock", ShipSkinKind.Stock, "#D8232C", "#86121F", "#FF5B45"),
            S("Night", ShipSkinKind.Palette, "#2A2E6B", "#1A1F45", "#6EF2EE"),
            S("Sodium", ShipSkinKind.Palette, "#F2862B", "#A9481A", "#FFB43C"),
            S("Bone", ShipSkinKind.Palette, "#F4EAD4", "#B9AE98", "#F4EAD4"),
            S("Kaneda", ShipSkinKind.Special, "#D8232C", "#86121F", "#FF5B45", "racing", "#F4EAD4", "#B9AE98", "#F4EAD4") },
        /*  2 VoltViper    */ new[] {
            S("Stock", ShipSkinKind.Stock, "#2E9BE6", "#174C8C", "#8FD3FF"),
            S("Night", ShipSkinKind.Palette, "#2A2E6B", "#1A1F45", "#6EF2EE"),
            S("Sodium", ShipSkinKind.Palette, "#F2862B", "#A9481A", "#FFB43C"),
            S("Bone", ShipSkinKind.Palette, "#F4EAD4", "#B9AE98", "#F4EAD4"),
            S("Storm", ShipSkinKind.Special, "#2E9BE6", "#174C8C", "#8FD3FF", "chevrons", "#FFB43C", "#F2862B", "#F4EAD4") },
        /*  3 SolarFang    */ new[] {
            S("Stock", ShipSkinKind.Stock, "#F07A1E", "#9A3E12", "#FFC27A"),
            S("Night", ShipSkinKind.Palette, "#2A2E6B", "#1A1F45", "#6EF2EE"),
            S("Neon", ShipSkinKind.Palette, "#1FB5B9", "#0F5E6A", "#6EF2EE"),
            S("Bone", ShipSkinKind.Palette, "#F4EAD4", "#B9AE98", "#F4EAD4"),
            S("Eclipse", ShipSkinKind.Special, "#F07A1E", "#9A3E12", "#FFC27A", "split", "#2C2D40", "#1A1A28", "#5A5C78") },
        /*  4 CrimsonHalo  */ new[] {
            S("Stock", ShipSkinKind.Stock, "#C8285E", "#6E1136", "#FF7AA2"),
            S("Night", ShipSkinKind.Palette, "#2A2E6B", "#1A1F45", "#6EF2EE"),
            S("Sodium", ShipSkinKind.Palette, "#F2862B", "#A9481A", "#FFB43C"),
            S("Bone", ShipSkinKind.Palette, "#F4EAD4", "#B9AE98", "#F4EAD4"),
            S("Seraph", ShipSkinKind.Special, "#C8285E", "#6E1136", "#FF7AA2", "chevrons", "#F4EAD4", "#B9AE98", "#F4EAD4") },
        /*  5 IonLancer    */ new[] {
            S("Stock", ShipSkinKind.Stock, "#3A5BE0", "#1C2A80", "#9AB0FF"),
            S("Night", ShipSkinKind.Palette, "#2A2E6B", "#1A1F45", "#6EF2EE"),
            S("Sodium", ShipSkinKind.Palette, "#F2862B", "#A9481A", "#FFB43C"),
            S("Bone", ShipSkinKind.Palette, "#F4EAD4", "#B9AE98", "#F4EAD4"),
            S("Lance", ShipSkinKind.Special, "#3A5BE0", "#1C2A80", "#9AB0FF", "racing", "#1FB5B9", "#0F5E6A", "#6EF2EE") },
        /*  6 JadePhantom  */ new[] {
            S("Stock", ShipSkinKind.Stock, "#22B07A", "#0E5A44", "#8EF0C4"),
            S("Night", ShipSkinKind.Palette, "#2A2E6B", "#1A1F45", "#6EF2EE"),
            S("Sodium", ShipSkinKind.Palette, "#F2862B", "#A9481A", "#FFB43C"),
            S("Bone", ShipSkinKind.Palette, "#F4EAD4", "#B9AE98", "#F4EAD4"),
            S("Wraith", ShipSkinKind.Special, "#22B07A", "#0E5A44", "#8EF0C4", "chevrons", "#2C2D40", "#1A1A28", "#5A5C78") },
        /*  7 GoldWarden   */ new[] {
            S("Stock", ShipSkinKind.Stock, "#D99A1A", "#7E4E0C", "#FFD36A"),
            S("Night", ShipSkinKind.Palette, "#2A2E6B", "#1A1F45", "#6EF2EE"),
            S("Neon", ShipSkinKind.Palette, "#1FB5B9", "#0F5E6A", "#6EF2EE"),
            S("Bone", ShipSkinKind.Palette, "#F4EAD4", "#B9AE98", "#F4EAD4"),
            S("Regent", ShipSkinKind.Special, "#D99A1A", "#7E4E0C", "#FFD36A", "split", "#2A2E6B", "#1A1F45", "#6EF2EE") },
        /*  8 Lightning    */ new[] {
            S("Stock", ShipSkinKind.Stock, "#EEDC32", "#8E8414", "#FFF6A8"),
            S("Night", ShipSkinKind.Palette, "#2A2E6B", "#1A1F45", "#6EF2EE"),
            S("Sodium", ShipSkinKind.Palette, "#F2862B", "#A9481A", "#FFB43C"),
            S("Bone", ShipSkinKind.Palette, "#F4EAD4", "#B9AE98", "#F4EAD4"),
            S("Hazard", ShipSkinKind.Special, "#EEDC32", "#8E8414", "#FFF6A8", "diagonal", "#2C2D40", "#1A1A28", "#5A5C78") },
        /*  9 Ligher       */ new[] {
            S("Stock", ShipSkinKind.Stock, "#C8662E", "#6E3014", "#F2A472"),
            S("Night", ShipSkinKind.Palette, "#2A2E6B", "#1A1F45", "#6EF2EE"),
            S("Amber", ShipSkinKind.Palette, "#FFB43C", "#F2862B", "#F4EAD4"),
            S("Bone", ShipSkinKind.Palette, "#F4EAD4", "#B9AE98", "#F4EAD4"),
            S("Flint", ShipSkinKind.Special, "#C8662E", "#6E3014", "#F2A472", "chevrons", "#F4EAD4", "#B9AE98", "#F4EAD4") },
        /* 10 Paranoid     */ new[] {
            S("Stock", ShipSkinKind.Stock, "#5DBB3A", "#2A5E1E", "#B6EE8A"),
            S("Night", ShipSkinKind.Palette, "#2A2E6B", "#1A1F45", "#6EF2EE"),
            S("Sodium", ShipSkinKind.Palette, "#F2862B", "#A9481A", "#FFB43C"),
            S("Bone", ShipSkinKind.Palette, "#F4EAD4", "#B9AE98", "#F4EAD4"),
            S("Signal", ShipSkinKind.Special, "#5DBB3A", "#2A5E1E", "#B6EE8A", "diagonal", "#FFB43C", "#F2862B", "#F4EAD4") },
        /* 11 Ninja        */ new[] {
            S("Stock", ShipSkinKind.Stock, "#4A58C8", "#232A6E", "#9FA8F0"),
            S("Night", ShipSkinKind.Palette, "#2A2E6B", "#1A1F45", "#6EF2EE"),
            S("Sodium", ShipSkinKind.Palette, "#F2862B", "#A9481A", "#FFB43C"),
            S("Bone", ShipSkinKind.Palette, "#F4EAD4", "#B9AE98", "#F4EAD4"),
            S("Ronin", ShipSkinKind.Special, "#4A58C8", "#232A6E", "#9FA8F0", "split", "#D8232C", "#86121F", "#FF5B45") },
        /* 12 Saboteur     */ new[] {
            S("Stock", ShipSkinKind.Stock, "#B83CC0", "#5E1A66", "#E89AF0"),
            S("Night", ShipSkinKind.Palette, "#2A2E6B", "#1A1F45", "#6EF2EE"),
            S("Sodium", ShipSkinKind.Palette, "#F2862B", "#A9481A", "#FFB43C"),
            S("Bone", ShipSkinKind.Palette, "#F4EAD4", "#B9AE98", "#F4EAD4"),
            S("Jester", ShipSkinKind.Special, "#B83CC0", "#5E1A66", "#E89AF0", "chevrons", "#1FB5B9", "#0F5E6A", "#6EF2EE") },
        /* 13 UFO          */ new[] {
            S("Stock", ShipSkinKind.Stock, "#7A52DC", "#3A2478", "#BBA4FF"),
            S("Night", ShipSkinKind.Palette, "#2A2E6B", "#1A1F45", "#6EF2EE"),
            S("Sodium", ShipSkinKind.Palette, "#F2862B", "#A9481A", "#FFB43C"),
            S("Bone", ShipSkinKind.Palette, "#F4EAD4", "#B9AE98", "#F4EAD4"),
            S("Abductor", ShipSkinKind.Special, "#7A52DC", "#3A2478", "#BBA4FF", "split", "#1FB5B9", "#0F5E6A", "#6EF2EE") },
        /* 14 Dove         */ new[] {
            S("Stock", ShipSkinKind.Stock, "#36C2C2", "#146A70", "#A6F2EE"),
            S("Night", ShipSkinKind.Palette, "#2A2E6B", "#1A1F45", "#6EF2EE"),
            S("Sodium", ShipSkinKind.Palette, "#F2862B", "#A9481A", "#FFB43C"),
            S("Bone", ShipSkinKind.Palette, "#F4EAD4", "#B9AE98", "#F4EAD4"),
            S("Courier", ShipSkinKind.Special, "#36C2C2", "#146A70", "#A6F2EE", "split", "#F4EAD4", "#B9AE98", "#F4EAD4") },
        /* 15 Turtle       */ new[] {
            S("Stock", ShipSkinKind.Stock, "#A87A3E", "#5A3A18", "#E2BE84"),
            S("Night", ShipSkinKind.Palette, "#2A2E6B", "#1A1F45", "#6EF2EE"),
            S("Sodium", ShipSkinKind.Palette, "#F2862B", "#A9481A", "#FFB43C"),
            S("Bone", ShipSkinKind.Palette, "#F4EAD4", "#B9AE98", "#F4EAD4"),
            S("Shellback", ShipSkinKind.Special, "#A87A3E", "#5A3A18", "#E2BE84", "chevrons", "#2C2D40", "#1A1A28", "#5A5C78") },
        // END GENERATED SKINS
    };

    public static bool Has(int id, int skin)
    {
        return id > 0 && id < table.Length && table[id] != null && skin >= 0 && skin < table[id].Length;
    }

    public static int CountFor(int id) { return id > 0 && id < table.Length && table[id] != null ? table[id].Length : 0; }

    public static ShipSkin Get(int id, int skin)
    {
        if (Has(id, skin)) return table[id][skin];
        if (Has(id, Stock)) return table[id][Stock];
        return S("Stock", ShipSkinKind.Stock, "#FFFFFF", "#FFFFFF", "#FFFFFF");
    }

    // Resource name of a non-stock sheet: "<ShipKey>_<SkinName>".
    public static string SheetName(int id, int skin)
    {
        string key = ShipId.KeyOf(id);
        return key == null || skin == Stock || !Has(id, skin) ? key : key + "_" + table[id][skin].name;
    }

    // ---------------------------------------------------------- keys

    // The strings are built once: the hull is drawn every frame (title-screen
    // traffic, the flying ship), and a per-frame string concat is garbage.
    const int KeyCacheShips = 32;
    static readonly string[] equippedKeys = new string[KeyCacheShips];
    static readonly string[] devKeys = new string[KeyCacheShips];
    static readonly string[] ownedKeys = new string[KeyCacheShips * PerShip];

    public static string EquippedKey(int id)
    {
        if (id < 0 || id >= KeyCacheShips) return EquippedKeyPrefix + id;
        return equippedKeys[id] ?? (equippedKeys[id] = EquippedKeyPrefix + id);
    }

    public static string OwnedKey(int id, int skin)
    {
        if (id < 0 || id >= KeyCacheShips || skin < 0 || skin >= PerShip) return OwnedKeyPrefix + id + "_" + skin;
        int k = id * PerShip + skin;
        return ownedKeys[k] ?? (ownedKeys[k] = OwnedKeyPrefix + id + "_" + skin);
    }

    public static string DeveloperEquippedKey(int id)
    {
        if (id < 0 || id >= KeyCacheShips) return DeveloperEquippedPrefix + id;
        return devKeys[id] ?? (devKeys[id] = DeveloperEquippedPrefix + id);
    }

    // ---------------------------------------------------------- ownership

    // The saved ownership, whatever developer mode shows.
    public static bool IsOwnedReal(int id, int skin)
    {
        if (!Has(id, skin)) return false;
        return skin == Stock || PlayerPrefs.GetInt(OwnedKey(id, skin), 0) == 1;
    }

    public static bool IsOwned(int id, int skin)
    {
        if (!Has(id, skin)) return false;
        return DeveloperUnlocks.Enabled || IsOwnedReal(id, skin);
    }

    // ---------------------------------------------------------- equipped

    // The saved choice, ignoring developer mode (what the cloud syncs).
    public static int EquippedReal(int id)
    {
        int skin = PlayerPrefs.GetInt(EquippedKey(id), Stock);
        return IsOwnedReal(id, skin) ? skin : Stock;
    }

    // The skin the ship flies in.
    public static int Equipped(int id)
    {
        if (DeveloperUnlocks.Enabled && PlayerPrefs.HasKey(DeveloperEquippedKey(id)))
        {
            int dev = PlayerPrefs.GetInt(DeveloperEquippedKey(id), Stock);
            return Has(id, dev) ? dev : Stock;
        }
        return EquippedReal(id);
    }

    // Equips an owned skin and saves at once. False (nothing written) if the
    // skin isn't owned.
    public static bool Equip(int id, int skin)
    {
        if (!IsOwned(id, skin)) return false;
        if (DeveloperUnlocks.Enabled) PlayerPrefs.SetInt(DeveloperEquippedKey(id), skin);
        else if (skin == Stock) PlayerPrefs.DeleteKey(EquippedKey(id));
        else PlayerPrefs.SetInt(EquippedKey(id), skin);
        if (previewShip == id) { previewShip = 0; previewSkin = Stock; }
        PrefsSaver.SaveNow();
        Raise(id);
        return true;
    }

    public enum PurchaseResult { Bought, AlreadyOwned, CantAfford, Invalid }

    // Spends the dust once, marks the skin owned, equips it and saves at once.
    public static PurchaseResult TryPurchase(int id, int skin)
    {
        if (!Has(id, skin) || !ShipId.IsOwned(id)) return PurchaseResult.Invalid;
        if (IsOwned(id, skin)) return PurchaseResult.AlreadyOwned;
        float price = PriceOf(id, skin);
        float dust = PlayerPrefs.GetFloat(StarDustLedger.CurrencyKey);
        if (dust < price) return PurchaseResult.CantAfford;
        PlayerPrefs.SetFloat(StarDustLedger.CurrencyKey, dust - price);
        PlayerPrefs.SetInt(OwnedKey(id, skin), 1);
        AchievementTracker.OnSkinBought(id, skin, price);
        Equip(id, skin);   // saves
        return PurchaseResult.Bought;
    }

    // Star dust still missing to buy a skin (0 if affordable).
    public static float ShortBy(int id, int skin)
    {
        return Mathf.Max(0f, PriceOf(id, skin) - PlayerPrefs.GetFloat(StarDustLedger.CurrencyKey));
    }

    // Developer mode switched off: forget its choices (the real ones were
    // never touched).
    public static void ClearDeveloperChoices()
    {
        for (int id = 1; id < table.Length; id++)
        {
            if (!PlayerPrefs.HasKey(DeveloperEquippedKey(id))) continue;
            PlayerPrefs.DeleteKey(DeveloperEquippedKey(id));
            Raise(id);
        }
    }

    // ---------------------------------------------------------- preview

    static int previewShip, previewSkin;

    public static bool IsPreviewing(int id) { return id > 0 && previewShip == id; }
    public static int PreviewShip { get { return previewShip; } }

    public static void SetPreview(int id, int skin)
    {
        if (!Has(id, skin)) return;
        int old = previewShip;
        if (skin == Equipped(id)) { previewShip = 0; previewSkin = Stock; }
        else { previewShip = id; previewSkin = skin; }
        if (old > 0 && old != id) Raise(old);
        Raise(id);
    }

    public static void ClearPreview()
    {
        int old = previewShip;
        previewShip = 0;
        previewSkin = Stock;
        if (old > 0) Raise(old);
    }

    // The skin the ship is drawn in right now: a dock preview, else equipped.
    public static int Shown(int id)
    {
        return previewShip == id && id > 0 ? previewSkin : Equipped(id);
    }

    // The colours the ship is drawn in right now (for the exhaust and any
    // per-ship tint). ShipSkins.Current(id).primary is the hull base colour.
    public static ShipSkin Current(int id) { return Get(id, Shown(id)); }

    static void Raise(int id)
    {
        if (Changed != null) Changed(id);
    }

    public static Color Parse(string hex)
    {
        Color c;
        return hex != null && ColorUtility.TryParseHtmlString(hex, out c) ? c : Color.white;
    }
}
