using System.Collections.Generic;
using UnityEngine;

// The player hulls' art: one flipbook sheet per ship, drawn in the Akira
// flat-cel style (docs/art-style.md) and generated by
// Art/Resources/ShipArt/Hulls/src~/build.py.
//
// Resources/ShipArt/Hulls/<ShipId.KeyOf(id)>.png is a grid of 256 px cells:
//   rows    = damage state, top to bottom (0 intact, 1 damaged, 2 critical)
//   columns = idle drawings 0..5, bank left, bank right, hit flash
// Every cell of a ship shares one sprite rect (the union of its art), so the
// pivot never jumps between frames: the bob and the bank are drawn inside it.
//
// Pixels-per-unit is chosen per ship so the rect has exactly the world size
// the old 2016 sprite had (its rect / 100). Everything that sizes itself off
// sprite.bounds -- NormalizedHullScale, the collider, the shield fit, the
// dock berth, the exhaust -- therefore keeps its numbers.
public static class ShipHullArt
{
    public const string Folder = "ShipArt/Hulls/";
    public const int Cell = 256;
    public const int Columns = 9;
    public const int States = 3;
    public const int IdleDrawings = 6;
    public const int BankLeft = 6, BankRight = 7, Hit = 8;

    // Flipbook timing, in 24 fps ticks ("on 2s and 3s"): (drawing, hold).
    // Rests on the key pose, bobs up, blinks the running lights, sweeps a
    // glint across the canopy, dips. 35 ticks, about 1.5 s a loop.
    public const float TicksPerSecond = 24f;
    // (Two flat arrays on purpose: TestHarness.Sandbox snapshots static
    // readonly collections, and a multi-dimensional array can't be copied.)
    static readonly int[] idleDrawing = { 0, 1, 2, 1, 0, 5, 0, 3, 4, 0, 5 };
    static readonly int[] idleHold = { 6, 3, 3, 3, 3, 3, 4, 2, 2, 3, 3 };

    public static int IdleLoopTicks
    {
        get
        {
            int total = 0;
            for (int i = 0; i < idleHold.Length; i++) total += idleHold[i];
            return total;
        }
    }

    // The idle drawing to show `ticks` (24 fps) into the loop.
    public static int IdleDrawingAt(float ticks)
    {
        int loop = IdleLoopTicks;
        int t = Mathf.FloorToInt(Mathf.Repeat(ticks, loop));
        for (int i = 0; i < idleHold.Length; i++)
        {
            t -= idleHold[i];
            if (t < 0) return idleDrawing[i];
        }
        return 0;
    }

    public struct HullRect
    {
        public int x, y, w, h;          // inside a cell, Unity's bottom-up pixels
        public float pixelsPerUnit;
        public string hue, hueShadow, hueHighlight;   // the ship's identity colour (#RRGGBB)
        public HullRect(int x, int y, int w, int h, float ppu, string hue = "#FFFFFF",
                        string hueShadow = "#FFFFFF", string hueHighlight = "#FFFFFF")
        {
            this.x = x; this.y = y; this.w = w; this.h = h; pixelsPerUnit = ppu;
            this.hue = hue; this.hueShadow = hueShadow; this.hueHighlight = hueHighlight;
        }
    }

    static readonly HullRect[] rects =
    {
        new HullRect(0, 0, Cell, Cell, 100f),
        // BEGIN GENERATED RECTS
        /*  1 NeonComet    */ new HullRect(7, 18, 243, 220, 759.3750f, "#D8232C", "#86121F", "#FF5B45"),
        /*  2 VoltViper    */ new HullRect(7, 28, 243, 200, 867.8571f, "#2E9BE6", "#174C8C", "#8FD3FF"),
        /*  3 SolarFang    */ new HullRect(7, 11, 242, 234, 834.4828f, "#F07A1E", "#9A3E12", "#FFC27A"),
        /*  4 CrimsonHalo  */ new HullRect(31, 7, 195, 242, 423.9130f, "#C8285E", "#6E1136", "#FF7AA2"),
        /*  5 IonLancer    */ new HullRect(25, 7, 207, 242, 440.4255f, "#3A5BE0", "#1C2A80", "#9AB0FF"),
        /*  6 JadePhantom  */ new HullRect(7, 9, 242, 238, 432.1429f, "#22B07A", "#0E5A44", "#8EF0C4"),
        /*  7 GoldWarden   */ new HullRect(16, 7, 224, 242, 439.2157f, "#D99A1A", "#7E4E0C", "#FFD36A"),
        /*  8 Lightning    */ new HullRect(7, 11, 243, 234, 867.8571f, "#EEDC32", "#8E8414", "#FFF6A8"),
        /*  9 Ligher       */ new HullRect(45, 7, 167, 242, 835.0000f, "#C8662E", "#6E3014", "#F2A472"),
        /* 10 Paranoid     */ new HullRect(7, 39, 243, 178, 810.0000f, "#5DBB3A", "#2A5E1E", "#B6EE8A"),
        /* 11 Ninja        */ new HullRect(7, 7, 242, 242, 806.6667f, "#4A58C8", "#232A6E", "#9FA8F0"),
        /* 12 Saboteur     */ new HullRect(31, 7, 194, 242, 808.3333f, "#B83CC0", "#5E1A66", "#E89AF0"),
        /* 13 UFO          */ new HullRect(7, 7, 242, 242, 930.7692f, "#7A52DC", "#3A2478", "#BBA4FF"),
        /* 14 Dove         */ new HullRect(27, 7, 202, 242, 1010.0000f, "#36C2C2", "#146A70", "#A6F2EE"),
        /* 15 Turtle       */ new HullRect(36, 7, 184, 242, 836.3636f, "#A87A3E", "#5A3A18", "#E2BE84"),
        // END GENERATED RECTS
    };

    public static bool Has(int id) { return id > 0 && id < rects.Length && ShipId.KeyOf(id) != null; }

    public static HullRect RectFor(int id) { return Has(id) ? rects[id] : rects[0]; }

    // The ship's identity hue: base, its one shadow, its one highlight. Red is
    // the starter's (Neon Comet) and every hull's friendly accent; the others
    // keep the hue their old art had. Handy for anything drawn per ship.
    public static Color[] IdentityHue(int id)
    {
        var r = RectFor(id);
        return new[] { Parse(r.hue), Parse(r.hueShadow), Parse(r.hueHighlight) };
    }

    static Color Parse(string hex)
    {
        Color c;
        return ColorUtility.TryParseHtmlString(hex, out c) ? c : Color.white;
    }

    static readonly Dictionary<int, Texture2D> sheets = new Dictionary<int, Texture2D>();
    static readonly Dictionary<int, Sprite> cache = new Dictionary<int, Sprite>();

    public static Texture2D SheetFor(int id)
    {
        if (!Has(id)) return null;
        Texture2D sheet;
        if (sheets.TryGetValue(id, out sheet) && sheet != null) return sheet;
        sheet = Resources.Load<Texture2D>(Folder + ShipId.KeyOf(id));
        sheets[id] = sheet;
        return sheet;
    }

    // One frame of ship `id`: damage `state` (0-2), `column` (0-8).
    public static Sprite Get(int id, int state, int column)
    {
        if (!Has(id)) return null;
        state = Mathf.Clamp(state, 0, States - 1);
        column = Mathf.Clamp(column, 0, Columns - 1);
        int key = (id * States + state) * Columns + column;
        Sprite sprite;
        if (cache.TryGetValue(key, out sprite) && sprite != null) return sprite;

        var sheet = SheetFor(id);
        if (sheet == null) return null;
        var r = rects[id];
        // rows run top to bottom in the png; Unity's rect origin is bottom-left
        int rowFromBottom = States - 1 - state;
        var rect = new Rect(column * Cell + r.x, rowFromBottom * Cell + r.y, r.w, r.h);
        sprite = Sprite.Create(sheet, rect, new Vector2(.5f, .5f), r.pixelsPerUnit, 0, SpriteMeshType.FullRect);
        sprite.name = ShipId.KeyOf(id) + "_" + state + "_" + column;
        cache[key] = sprite;
        return sprite;
    }

    public static Sprite Rest(int id, int state = 0) { return Get(id, state, 0); }
    public static Sprite Idle(int id, int state, int drawing) { return Get(id, state, Mathf.Clamp(drawing, 0, IdleDrawings - 1)); }
}
