using UnityEngine;

// Per-hull engine nozzle positions, measured off each ship's own pixel art.
//
// Exhaust used to be mounted with one shared rule: "bottom edge of the
// sprite, plus/minus a fraction of its width for the twin-engine ships".
// That only works when the engines happen to sit on the bottom edge at that
// fraction. Paranoid's two engines are outboard pods at the far left and
// right of the hull, 2px above its bottom edge -- the shared rule put its
// plumes ~5px inboard of them, under the belly. Crimson Halo, Ion Lancer and
// Jade Phantom have twin engines the rule treated as one centre nozzle, and
// Volt Viper's twin mounts landed outside its two exhaust legs.
//
// Each entry is in sprite-rect pixels: x from the rect's left edge, y from
// its bottom edge, at the nozzle's exit (where the plume should begin). The
// rects are ShipHullArt's (256 px cells of the Akira hull sheets). The rows
// are generated by Art/Resources/ShipArt/Hulls/src~/build.py, which takes
// each nozzle from the drawing and re-measures it on the rendered rest frame:
// it walks down the nozzle's own pixel column to the last painted row and
// sits the point just inside that lip. ShipNozzlesTest checks every point
// lies on painted pixels in the lower half of its hull.
public static class ShipNozzles
{
    public struct Nozzle
    {
        public float x, y;     // sprite-rect pixels
        public float scale;    // plume size relative to a single main engine
        public Nozzle(float x, float y, float scale) { this.x = x; this.y = y; this.scale = scale; }
    }

    const float Twin = .72f;

    static readonly Nozzle[][] table =
    {
        null,
        // BEGIN GENERATED NOZZLES
        /*  1 NeonComet    243x220 */ new[] { N(98.5f, 8.5f, Twin), N(144.5f, 8.5f, Twin) },
        /*  2 VoltViper    243x200 */ new[] { N(99.5f, 8.5f, Twin), N(143.5f, 8.5f, Twin) },
        /*  3 SolarFang    242x234 */ new[] { N(121.5f, 12.5f) },
        /*  4 CrimsonHalo  195x242 */ new[] { N(89.5f, 11.5f, Twin), N(105.5f, 12.5f, Twin) },
        /*  5 IonLancer    207x242 */ new[] { N(86.5f, 8.5f, Twin), N(120.5f, 8.5f, Twin) },
        /*  6 JadePhantom  242x238 */ new[] { N(113.5f, 12.5f, Twin), N(129.5f, 12.5f, Twin) },
        /*  7 GoldWarden   224x242 */ new[] { N(112.5f, 8.5f), N(75.5f, 24.5f, 0.5f), N(149.5f, 24.5f, 0.5f) },
        /*  8 Lightning    243x234 */ new[] { N(79.5f, 8.5f, Twin), N(163.5f, 8.5f, Twin) },
        /*  9 Ligher       167x242 */ new[] { N(83.5f, 8.5f) },
        /* 10 Paranoid     243x178 */ new[] { N(28.5f, 10.5f, Twin), N(214.5f, 10.5f, Twin) },
        /* 11 Ninja        242x242 */ new[] { N(121.5f, 47.5f) },
        /* 12 Saboteur     194x242 */ new[] { N(97.5f, 8.5f) },
        /* 13 UFO          242x242 */ new[] { N(121.5f, 44.5f) },
        /* 14 Dove         202x242 */ new[] { N(101.5f, 8.5f) },
        /* 15 Turtle       184x242 */ new[] { N(92.5f, 8.5f) },
        // END GENERATED NOZZLES
    };

    static readonly Nozzle[] fallback = { N(-1f, -1f) };

    static Nozzle N(float x, float y, float scale = 1f) { return new Nozzle(x, y, scale); }

    public static bool Has(int index)
    {
        return index > 0 && index < table.Length && table[index] != null && table[index].Length > 0;
    }

    public static Nozzle[] For(int index)
    {
        return Has(index) ? table[index] : fallback;
    }

    // Sprite-rect pixels -> the hull's local space. The fallback (negative
    // coordinates) means "centre of the bottom edge" for an unknown hull.
    public static Vector2 ToLocal(Sprite hull, Nozzle nozzle)
    {
        Rect rect = hull.rect;
        float px = nozzle.x < 0f ? rect.width * .5f : nozzle.x;
        float py = nozzle.y < 0f ? 1f : nozzle.y;
        return (new Vector2(px, py) - hull.pivot) / hull.pixelsPerUnit;
    }
}
