using UnityEngine;

// Engine plumes: one themed flipbook per ship, one plume per nozzle.
//
// The look of each ship's exhaust (its theme, colours, frames and timing)
// lives in ShipExhaustStyle; the art is ShipArt/Exhaust/exhaust_atlas
// (generated by Art/Resources/ShipArt/Hulls/src~/exhaust.py). Plume sprites
// are pivoted at the flame head, so the plume's top stays on the nozzle
// (ShipNozzles) while its length changes. This class mounts and sizes them.
//
// The two spinners (Ninja, UFO) have no nozzle plume: ShipSpinDrift draws
// their spin drift instead (a ring that turns with the hull and a wake).
public static class ShipExhaust
{
    public static int IndexFor(GameObject ship)
    {
        int id = ShipId.Of(ship);
        if (id != ShipId.None) return id;
        // Ships not named "ship<N>" (the title-screen traffic) are known by
        // their hull art: ShipHullArt names every frame "<Key>_<state>_<col>".
        var hull = ship != null ? ship.GetComponent<SpriteRenderer>() : null;
        id = hull != null ? IdOfHullSprite(hull.sprite) : ShipId.None;
        return id != ShipId.None ? id : ShipId.Starter;
    }

    public static int IdOfHullSprite(Sprite sprite)
    {
        if (sprite == null) return ShipId.None;
        string name = sprite.name;
        int cut = name.IndexOf('_');
        return ShipId.FromKey(cut > 0 ? name.Substring(0, cut) : name);
    }

    // Ninja and UFO are spinning craft, not nozzle-driven ships: a fixed
    // plume would rotate around with the hull and read as a broken flame,
    // so they get the spin drift (ShipSpinDrift) instead.
    public static bool UsesWind(int index) { return UsesSpinDrift(index); }

    public static bool UsesSpinDrift(int index)
    {
        return ShipExhaustStyle.IsSpinDrift(index);
    }

    // The plume's rest drawing (the flipbook starts here).
    public static Sprite SpriteFor(int index)
    {
        return Frame(index, false, 0);
    }

    public static Sprite Frame(int index, bool boost, int frame)
    {
        return ShipExhaustStyle.Frame(index, boost ? ExhaustLayer.PlumeBoost : ExhaustLayer.Plume, frame);
    }

    public static int FrameCount(int index) { return ShipExhaustStyle.FrameCount(index, ExhaustLayer.Plume); }

    // The drawing to show `ticks` (24 fps) into ship `index`'s loop.
    public static int FrameAt(int index, float ticks) { return ShipExhaustStyle.FrameAt(index, ticks); }

    public static Color TintFor(int index)
    {
        // The plumes are drawn in their final per-ship colours
        // (ShipExhaustStyle); ExhaustColors owns the multiplier.
        return ExhaustColors.Tint(index);
    }

    public static Vector3 MountFor(Sprite hull, int index)
    {
        var mounts = MountsFor(hull, index);
        return mounts.Length > 0 ? mounts[0] : new Vector3(0f, -.2f, .05f);
    }

    // Where each plume leaves the hull, in the hull's local space. Read from
    // ShipNozzles' per-ship pixel table, so the flight flame, the dock flame
    // and the launch flare all leave the same painted nozzles.
    public static Vector3[] MountsFor(Sprite hull, int index)
    {
        if (hull == null) return new[] { new Vector3(0f, -.2f, .05f) };
        var nozzles = ShipNozzles.For(index);
        var mounts = new Vector3[nozzles.Length];
        for (int i = 0; i < nozzles.Length; i++)
        {
            Vector2 local = ShipNozzles.ToLocal(hull, nozzles[i]);
            mounts[i] = new Vector3(local.x, local.y, .05f);
        }
        return mounts;
    }

    // Relative plume size per nozzle: a twin-engine ship splits its thrust,
    // and small auxiliary nozzles get a smaller flame than the main one.
    public static float NozzleScale(int index, int nozzle)
    {
        var nozzles = ShipNozzles.For(index);
        if (nozzle < 0 || nozzle >= nozzles.Length) return 1f;
        return nozzles[nozzle].scale;
    }

    public static Vector3 ScaleFor(Sprite hull, int index)
    {
        var sprite = SpriteFor(index);
        if (hull == null || sprite == null) return Vector3.one * .2f;
        float height = hull.bounds.size.y;
        return new Vector3(height * (.22f + (index % 3) * .025f) / sprite.bounds.size.x,
                           height * (.65f + (index % 5) * .045f) / sprite.bounds.size.y, 1f);
    }

    public static GameObject ConfigureBoost(GameObject ship, int index)
    {
        GameObject boost = null;
        foreach (var child in ship.GetComponentsInChildren<Transform>(true))
            if (child != ship.transform && (child.CompareTag("boost") || child.name.StartsWith("Boost")))
            { boost = child.gameObject; break; }
        if (boost == null)
        {
            boost = new GameObject("Boost" + index);
            boost.transform.SetParent(ship.transform, false);
            boost.SetActive(false);
        }
        boost.name = "Boost" + index;
        boost.tag = "boost";
        if (UsesSpinDrift(index))
        {
            // collisionDetection still uses this tagged holder for the
            // blue-atom state (ShipSpinDrift reads it to switch to its boost
            // drawings). Leave the object discoverable, but disable all
            // visual renderers so a spinning craft never gains a flame.
            foreach (var renderer in boost.GetComponentsInChildren<SpriteRenderer>(true))
                renderer.enabled = false;
            return boost;
        }
        var animator = boost.GetComponent<Animator>();
        if (animator != null) animator.enabled = false;
        var hull = ship.GetComponent<SpriteRenderer>();
        // The root is what the legacy boost scripts activate. Actual plume
        // renderers are its children so a twin-engine ship gets twin flames.
        var rootRenderer = boost.GetComponent<SpriteRenderer>();
        if (rootRenderer != null) rootRenderer.enabled = false;
        var rootAnimation = boost.GetComponent<DockLaunchFlame>();
        if (rootAnimation != null) rootAnimation.enabled = false;
        boost.transform.localPosition = Vector3.zero;
        boost.transform.localRotation = Quaternion.identity;
        boost.transform.localScale = Vector3.one;
        var mounts = MountsFor(hull != null ? hull.sprite : null, index);
        var scale = ScaleFor(hull != null ? hull.sprite : null, index);
        for (int i = 0; i < mounts.Length; i++)
        {
            var child = boost.transform.Find("Nozzle" + i);
            var plume = child != null ? child.gameObject : new GameObject("Nozzle" + i);
            if (child == null) plume.transform.SetParent(boost.transform, false);
            var sr = plume.GetComponent<SpriteRenderer>();
            if (sr == null) sr = plume.AddComponent<SpriteRenderer>();
            sr.enabled = true;
            sr.sprite = Frame(index, true, 0);
            sr.color = TintFor(index);
            sr.sortingOrder = hull != null ? hull.sortingOrder - 1 : 3;
            plume.transform.localPosition = mounts[i];
            plume.transform.localRotation = Quaternion.identity;
            float k = NozzleScale(index, i);
            // The boost drawings are longer and hotter; shown longer still.
            plume.transform.localScale = new Vector3(scale.x * k,
                                                     scale.y * Mathf.Sqrt(k) * ShipExhaustStyle.BoostLength, scale.z);
            var animation = plume.GetComponent<DockLaunchFlame>();
            if (animation == null) animation = plume.AddComponent<DockLaunchFlame>();
            animation.Refresh();
            ShipFlameFlipbook.Attach(sr, i, index, true);
        }
        // A hull that changed to one with fewer nozzles leaves no stale plume.
        for (int i = mounts.Length; ; i++)
        {
            var stale = boost.transform.Find("Nozzle" + i);
            if (stale == null) break;
            Discard(stale.gameObject);
        }
        return boost;
    }

    // Removes a generated child now (renamed first, so a Find in the same
    // frame can't return it while Destroy is pending).
    public static void Discard(GameObject go)
    {
        if (go == null) return;
        go.name = "~discarded";
        go.SetActive(false);
        if (Application.isPlaying) Object.Destroy(go);
        else Object.DestroyImmediate(go);
    }
}
