using UnityEngine;

// Engine plumes: the Akira tail-light streak (docs/art-style.md, "Light
// trails"), one flipbook per nozzle. The art is ShipArt/Exhaust/trail_strip
// (generated by Art/Resources/ShipArt/Hulls/src~/exhaust.py): six 64x256
// frames, a red streak with a sodium middle, a bone core and a hard shock
// diamond, frame 2 the 1-tick smear with cyan speed lines. Each sprite is
// pivoted at the flame head, so the plume's top stays on the nozzle while
// its length changes.
public static class ShipExhaust
{
    public const string StripPath = "ShipArt/Exhaust/trail_strip";
    public const int FrameCount = 6;
    const int FrameWidth = 64, FrameHeight = 256;
    const float HeadPivotY = 1f - 3f / 128f;     // flame head, 3 u below the frame top
    // Hold of each frame in 24 fps ticks: on 2s, smear on 1 (the sample's).
    public static readonly int[] FrameTicks = { 2, 2, 1, 2, 2, 2 };

    static readonly Sprite[] frames = new Sprite[FrameCount];

    public static int IndexFor(GameObject ship)
    {
        return ShipId.Of(ship, ShipId.Starter);
    }

    // Ninja and UFO are spinning craft, not nozzle-driven ships. A fixed
    // exhaust would rotate around with the hull and read as a broken flame.
    public static bool UsesWind(int index)
    {
        return index == 11 || index == 13;
    }

    // The plume's rest frame (the flipbook starts here).
    public static Sprite SpriteFor(int index)
    {
        return Frame(0);
    }

    public static Sprite Frame(int frame)
    {
        frame = ((frame % FrameCount) + FrameCount) % FrameCount;
        if (frames[frame] == null)
        {
            var tex = Resources.Load<Texture2D>(StripPath);
            if (tex == null) return null;
            frames[frame] = Sprite.Create(tex, new Rect(frame * FrameWidth, 0, FrameWidth, FrameHeight),
                                          new Vector2(.5f, HeadPivotY), 100f, 0, SpriteMeshType.FullRect);
            frames[frame].name = "trail_" + frame;
        }
        return frames[frame];
    }

    // The frame to show `ticks` (24 fps) into the loop.
    public static int FrameAt(float ticks)
    {
        int loop = 0;
        foreach (int t in FrameTicks) loop += t;
        int at = Mathf.FloorToInt(Mathf.Repeat(ticks, loop));
        for (int i = 0; i < FrameTicks.Length; i++)
        {
            at -= FrameTicks[i];
            if (at < 0) return i;
        }
        return 0;
    }

    public static Color TintFor(int index)
    {
        // The streak is drawn in its final palette colours (red is the
        // player's friendly accent on every hull); a tint would only muddy
        // it. Each ship's engine still differs in plume size and length.
        return new Color(1f, 1f, 1f, .96f);
    }

    public static Vector3 MountFor(Sprite hull, int index)
    {
        var mounts = MountsFor(hull, index);
        return mounts.Length > 0 ? mounts[0] : new Vector3(0f, -.2f, .05f);
    }

    // Where each plume leaves the hull, in the hull's local space. Read from
    // ShipNozzles' per-ship pixel table, so the flight flame, the dock flame
    // and the launch flare all leave the same painted nozzles.
    public static Vector3[] MountsFor(Sprite hull, int index)
    {
        if (hull == null) return new[] { new Vector3(0f, -.2f, .05f) };
        var nozzles = ShipNozzles.For(index);
        var mounts = new Vector3[nozzles.Length];
        for (int i = 0; i < nozzles.Length; i++)
        {
            Vector2 local = ShipNozzles.ToLocal(hull, nozzles[i]);
            mounts[i] = new Vector3(local.x, local.y, .05f);
        }
        return mounts;
    }

    // Relative plume size per nozzle: a twin-engine ship splits its thrust,
    // and small auxiliary nozzles get a smaller flame than the main one.
    public static float NozzleScale(int index, int nozzle)
    {
        var nozzles = ShipNozzles.For(index);
        if (nozzle < 0 || nozzle >= nozzles.Length) return 1f;
        return nozzles[nozzle].scale;
    }

    public static Vector3 ScaleFor(Sprite hull, int index)
    {
        var sprite = SpriteFor(index);
        if (hull == null || sprite == null) return Vector3.one * .2f;
        float height = hull.bounds.size.y;
        return new Vector3(height * (.22f + (index % 3) * .025f) / sprite.bounds.size.x,
                           height * (.65f + (index % 5) * .045f) / sprite.bounds.size.y, 1f);
    }

    public static GameObject ConfigureBoost(GameObject ship, int index)
    {
        GameObject boost = null;
        foreach (var child in ship.GetComponentsInChildren<Transform>(true))
            if (child != ship.transform && (child.CompareTag("boost") || child.name.StartsWith("Boost")))
            { boost = child.gameObject; break; }
        if (boost == null)
        {
            boost = new GameObject("Boost" + index);
            boost.transform.SetParent(ship.transform, false);
            boost.SetActive(false);
        }
        boost.name = "Boost" + index;
        boost.tag = "boost";
        if (UsesWind(index))
        {
            // collisionDetection still uses this tagged holder for the old
            // blue-atom state. Leave the object discoverable, but disable all
            // visual renderers so a spinning craft never gains a flame.
            foreach (var renderer in boost.GetComponentsInChildren<SpriteRenderer>(true))
                renderer.enabled = false;
            return boost;
        }
        var animator = boost.GetComponent<Animator>();
        if (animator != null) animator.enabled = false;
        var hull = ship.GetComponent<SpriteRenderer>();
        // The root is what the legacy boost scripts activate. Actual plume
        // renderers are its children so a twin-engine ship gets twin flames.
        var rootRenderer = boost.GetComponent<SpriteRenderer>();
        if (rootRenderer != null) rootRenderer.enabled = false;
        var rootAnimation = boost.GetComponent<DockLaunchFlame>();
        if (rootAnimation != null) rootAnimation.enabled = false;
        boost.transform.localPosition = Vector3.zero;
        boost.transform.localRotation = Quaternion.identity;
        boost.transform.localScale = Vector3.one;
        var mounts = MountsFor(hull != null ? hull.sprite : null, index);
        var scale = ScaleFor(hull != null ? hull.sprite : null, index);
        for (int i = 0; i < mounts.Length; i++)
        {
            var child = boost.transform.Find("Nozzle" + i);
            var plume = child != null ? child.gameObject : new GameObject("Nozzle" + i);
            if (child == null) plume.transform.SetParent(boost.transform, false);
            var sr = plume.GetComponent<SpriteRenderer>();
            if (sr == null) sr = plume.AddComponent<SpriteRenderer>();
            sr.sprite = SpriteFor(index);
            sr.color = TintFor(index);
            sr.sortingOrder = hull != null ? hull.sortingOrder - 1 : 3;
            plume.transform.localPosition = mounts[i];
            plume.transform.localRotation = Quaternion.identity;
            float k = NozzleScale(index, i);
            plume.transform.localScale = new Vector3(scale.x * k, scale.y * Mathf.Sqrt(k), scale.z);
            var animation = plume.GetComponent<DockLaunchFlame>();
            if (animation == null) animation = plume.AddComponent<DockLaunchFlame>();
            animation.Refresh();
            ShipFlameFlipbook.Attach(sr, i);
        }
        return boost;
    }
}
